/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const E_STAR_GlyphWriteResult = {
	"Success": 0,
	"InvalidMessage": 1,
	"InvalidJSON": 2,
	"SQLError": 3,

	// Value-to-name mapping for convenience
	"0": "Success",
	"1": "InvalidMessage",
	"2": "InvalidJSON",
	"3": "SQLError",
};

module.exports = E_STAR_GlyphWriteResult;
