/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EAccountType = {
	"Invalid": 0,
	"Individual": 1,
	"Multiseat": 2,
	"GameServer": 3,
	"AnonGameServer": 4,
	"Pending": 5,
	"ContentServer": 6,
	"Clan": 7,
	"Chat": 8,
	"ConsoleUser": 9,
	"AnonUser": 10,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Individual",
	"2": "Multiseat",
	"3": "GameServer",
	"4": "AnonGameServer",
	"5": "Pending",
	"6": "ContentServer",
	"7": "Clan",
	"8": "Chat",
	"9": "ConsoleUser",
	"10": "AnonUser",
};

module.exports = EAccountType;
