/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EACState = {
	"Unknown": 0,
	"Disconnected": 1,
	"Connected": 2,
	"ConnectedSlow": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Disconnected",
	"2": "Connected",
	"3": "ConnectedSlow",
};

module.exports = EACState;
