/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EAppAssociationType = {
	"Invalid": 0,
	"Publisher": 1,
	"Developer": 2,
	"Franchise": 3,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Publisher",
	"2": "Developer",
	"3": "Franchise",
};

module.exports = EAppAssociationType;
