/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EAppControllerSupportLevel = {
	"None": 0,
	"Partial": 1,
	"Full": 2,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Partial",
	"2": "Full",
};

module.exports = EAppControllerSupportLevel;
