/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAppCloudStatus = {
	"Invalid": 0,
	"Disabled": 1,
	"Unknown": 2,
	"Synchronized": 3,
	"Checking": 4,
	"OutOfSync": 5,
	"Uploading": 6,
	"Downloading": 7,
	"SyncFailed": 8,
	"Conflict": 9,
	"PendingElsewhere": 10,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Disabled",
	"2": "Unknown",
	"3": "Synchronized",
	"4": "Checking",
	"5": "OutOfSync",
	"6": "Uploading",
	"7": "Downloading",
	"8": "SyncFailed",
	"9": "Conflict",
	"10": "PendingElsewhere",
};

module.exports = EAppCloudStatus;
