/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAppGamepadGyroTrackpadSupportLevel = {
	"Unknown": -1,
	"NoGamepad": 0,
	"Gamepad": 1,
	"Simultaneous": 2,

	// Value-to-name mapping for convenience
	"-1": "Unknown",
	"0": "NoGamepad",
	"1": "Gamepad",
	"2": "Simultaneous",
};

module.exports = EAppGamepadGyroTrackpadSupportLevel;
