/* eslint-disable */
// Auto-generated by generate-enums script on Mon Oct 17 2022 00:47:41 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAuthTokenRevokeAction = {
	"k_EAuthTokenRevokeLogout": 0,
	"k_EAuthTokenRevokePermanent": 1,
	"k_EAuthTokenRevokeReplaced": 2,
	"k_EAuthTokenRevokeSupport": 3,

	// Value-to-name mapping for convenience
	"0": "k_EAuthTokenRevokeLogout",
	"1": "k_EAuthTokenRevokePermanent",
	"2": "k_EAuthTokenRevokeReplaced",
	"3": "k_EAuthTokenRevokeSupport",
};

module.exports = EAuthTokenRevokeAction;
