/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAuthTokenState = {
	"Invalid": 0,
	"New": 1,
	"Confirmed": 2,
	"Issued": 3,
	"Denied": 4,
	"LoggedOut": 5,
	"Revoked": 99,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "New",
	"2": "Confirmed",
	"3": "Issued",
	"4": "Denied",
	"5": "LoggedOut",
	"99": "Revoked",
};

module.exports = EAuthTokenState;
