/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAuthSessionSecurityHistory = {
	"Invalid": 0,
	"UsedPreviously": 1,
	"NoPriorHistory": 2,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "UsedPreviously",
	"2": "NoPriorHistory",
};

module.exports = EAuthSessionSecurityHistory;
