/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAuthTokenRevokeAction = {
	"Logout": 0,
	"Permanent": 1,
	"Replaced": 2,
	"Support": 3,
	"Consume": 4,
	"NonRememberedLogout": 5,
	"NonRememberedPermanent": 6,
	"Automatic": 7,

	// Value-to-name mapping for convenience
	"0": "Logout",
	"1": "Permanent",
	"2": "Replaced",
	"3": "Support",
	"4": "Consume",
	"5": "NonRememberedLogout",
	"6": "NonRememberedPermanent",
	"7": "Automatic",
};

module.exports = EAuthTokenRevokeAction;
