/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:40:14 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAuthSessionGuardType = {
	"Unknown": 0,
	"None": 1,
	"EmailCode": 2,
	"DeviceCode": 3,
	"DeviceConfirmation": 4,
	"EmailConfirmation": 5,
	"MachineToken": 6,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "None",
	"2": "EmailCode",
	"3": "DeviceCode",
	"4": "DeviceConfirmation",
	"5": "EmailConfirmation",
	"6": "MachineToken",
};

module.exports = EAuthSessionGuardType;
