/* eslint-disable */
// Auto-generated by generate-enums script on Mon Oct 17 2022 00:49:16 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EAuthTokenRevokeAction = {
	"Logout": 0,
	"Permanent": 1,
	"Replaced": 2,
	"Support": 3,

	// Value-to-name mapping for convenience
	"0": "Logout",
	"1": "Permanent",
	"2": "Replaced",
	"3": "Support",
};

module.exports = EAuthTokenRevokeAction;
