/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EBatteryState = {
	"Unknown": 0,
	"Discharging": 1,
	"Charging": 2,
	"Full": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Discharging",
	"2": "Charging",
	"3": "Full",
};

module.exports = EBatteryState;
