/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:35:51 GMT-0500 (Eastern Standard Time)

/**
 * @enum EBluetoothDeviceType
 * @readonly
 */
const EBluetoothDeviceType = {
	"Invalid": 0,
	"Unknown": 1,
	"Phone": 2,
	"Computer": 3,
	"Headset": 4,
	"Headphones": 5,
	"Speakers": 6,
	"OtherAudio": 7,
	"Mouse": 8,
	"Joystick": 9,
	"Gamepad": 10,
	"Keyboard": 11,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Unknown",
	"2": "Phone",
	"3": "Computer",
	"4": "Headset",
	"5": "Headphones",
	"6": "Speakers",
	"7": "OtherAudio",
	"8": "Mouse",
	"9": "Joystick",
	"10": "Gamepad",
	"11": "Keyboard",
};

module.exports = EBluetoothDeviceType;
