/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EBroadcastImageType = {
	"None": 0,
	"Offline": 1,
	"Standby": 2,
	"Avatar": 3,
	"Summary": 4,
	"Background": 5,
	"Emoticon": 6,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Offline",
	"2": "Standby",
	"3": "Avatar",
	"4": "Summary",
	"5": "Background",
	"6": "Emoticon",
};

module.exports = EBroadcastImageType;
