/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EChatRoomJoinState = {
	"Default": 0,
	"None": 1,
	"Joined": 2,
	"TestInvalid": 99,

	// Value-to-name mapping for convenience
	"0": "Default",
	"1": "None",
	"2": "Joined",
	"99": "TestInvalid",
};

module.exports = EChatRoomJoinState;
