/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EChatRoomType = {
	"Friend": 1,
	"MUC": 2,
	"Lobby": 3,

	// Value-to-name mapping for convenience
	"1": "Friend",
	"2": "MUC",
	"3": "Lobby",
};

module.exports = EChatRoomType;
