/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EChatRoomNotificationLevel = {
	"Invalid": 0,
	"None": 1,
	"MentionMe": 2,
	"MentionAll": 3,
	"AllMessages": 4,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "None",
	"2": "MentionMe",
	"3": "MentionAll",
	"4": "AllMessages",
};

module.exports = EChatRoomNotificationLevel;
