/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EChatInfoType = {
	"StateChange": 1,
	"InfoUpdate": 2,
	"MemberLimitChange": 3,

	// Value-to-name mapping for convenience
	"1": "StateChange",
	"2": "InfoUpdate",
	"3": "MemberLimitChange",
};

module.exports = EChatInfoType;
