/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EChatFlags = {
	"Locked": 1,
	"InvisibleToFriends": 2,
	"Moderated": 4,
	"Unjoinable": 8,

	// Value-to-name mapping for convenience
	"1": "Locked",
	"2": "InvisibleToFriends",
	"4": "Moderated",
	"8": "Unjoinable",
};

module.exports = EChatFlags;
