/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EClanRank = {
	"None": 0,
	"Owner": 1,
	"Officer": 2,
	"Member": 3,
	"Moderator": 4,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Owner",
	"2": "Officer",
	"3": "Member",
	"4": "Moderator",
};

module.exports = EClanRank;
