/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EClientStatAggregateMethod = {
	"LatestOnly": 0,
	"Sum": 1,
	"Event": 2,
	"Scalar": 3,

	// Value-to-name mapping for convenience
	"0": "LatestOnly",
	"1": "Sum",
	"2": "Event",
	"3": "Scalar",
};

module.exports = EClientStatAggregateMethod;
