/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EClientStat = {
	"P2PConnectionsUDP": 0,
	"P2PConnectionsRelay": 1,
	"P2PGameConnections": 2,
	"P2PVoiceConnections": 3,
	"BytesDownloaded": 4,

	// Value-to-name mapping for convenience
	"0": "P2PConnectionsUDP",
	"1": "P2PConnectionsRelay",
	"2": "P2PGameConnections",
	"3": "P2PVoiceConnections",
	"4": "BytesDownloaded",
};

module.exports = EClientStat;
