/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EClientSettingStore = {
	"Invalid": 0,
	"ConfigStore_Install": 1,
	"ConfigStore_UserRoaming": 2,
	"ConfigStore_UserLocal": 3,
	"Registry": 4,
	"CustomFunc": 5,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "ConfigStore_Install",
	"2": "ConfigStore_UserRoaming",
	"3": "ConfigStore_UserLocal",
	"4": "Registry",
	"5": "CustomFunc",
};

module.exports = EClientSettingStore;
