/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ECodecUsageReason = {
	"Unknown": 0,
	"RemotePlay": 1,
	"Broadcasting": 2,
	"GameVideo": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "RemotePlay",
	"2": "Broadcasting",
	"3": "GameVideo",
};

module.exports = ECodecUsageReason;
