/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ECodecUsagePlatform = {
	"Unknown": 0,
	"Windows": 1,
	"MacOS": 2,
	"Linux": 3,
	"SteamDeck": 4,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Windows",
	"2": "MacOS",
	"3": "Linux",
	"4": "SteamDeck",
};

module.exports = ECodecUsagePlatform;
