/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EColorProfile = {
	"Invalid": 0,
	"Native": 1,
	"Standard": 2,
	"Vivid": 3,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Native",
	"2": "Standard",
	"3": "Vivid",
};

module.exports = EColorProfile;
