/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ECommunityItemClass = {
	"Invalid": 0,
	"Badge": 1,
	"GameCard": 2,
	"ProfileBackground": 3,
	"Emoticon": 4,
	"BoosterPack": 5,
	"Consumable": 6,
	"GameGoo": 7,
	"ProfileModifier": 8,
	"Scene": 9,
	"SalienItem": 10,
	"Sticker": 11,
	"ChatEffect": 12,
	"MiniProfileBackground": 13,
	"AvatarFrame": 14,
	"AnimatedAvatar": 15,
	"SteamDeckKeyboardSkin": 16,
	"SteamDeckStartupMovie": 17,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Badge",
	"2": "GameCard",
	"3": "ProfileBackground",
	"4": "Emoticon",
	"5": "BoosterPack",
	"6": "Consumable",
	"7": "GameGoo",
	"8": "ProfileModifier",
	"9": "Scene",
	"10": "SalienItem",
	"11": "Sticker",
	"12": "ChatEffect",
	"13": "MiniProfileBackground",
	"14": "AvatarFrame",
	"15": "AnimatedAvatar",
	"16": "SteamDeckKeyboardSkin",
	"17": "SteamDeckStartupMovie",
};

module.exports = ECommunityItemClass;
