/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EContentDeltaChunkDataLocation = {
	"InProtobuf": 0,
	"AfterProtobuf": 1,

	// Value-to-name mapping for convenience
	"0": "InProtobuf",
	"1": "AfterProtobuf",
};

module.exports = EContentDeltaChunkDataLocation;
