/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EContentDescriptorID = {
	"FrequentNudityOrSexualContent": 1,
	"FrequentViolenceOrGore": 2,
	"StrongSexualContent": 3,
	"UNUSED_4": 4,
	"AnyMatureContent": 5,

	// Value-to-name mapping for convenience
	"1": "FrequentNudityOrSexualContent",
	"2": "FrequentViolenceOrGore",
	"3": "StrongSexualContent",
	"4": "UNUSED_4",
	"5": "AnyMatureContent",
};

module.exports = EContentDescriptorID;
