/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EContentHubDiscountFilterType = {
	"None": 0,
	"DiscountsOnly": 1,
	"PrioritizeDiscounts": 2,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "DiscountsOnly",
	"2": "PrioritizeDiscounts",
};

module.exports = EContentHubDiscountFilterType;
