/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ECPUGovernor = {
	"Invalid": 0,
	"Perf": 1,
	"Powersave": 2,
	"Manual": 3,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Perf",
	"2": "Powersave",
	"3": "Manual",
};

module.exports = ECPUGovernor;
