/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EDRMBlobDownloadType = {
	"Error": 0,
	"File": 1,
	"Parts": 2,
	"Compressed": 4,
	"AllMask": 7,
	"IsJob": 8,
	"HighPriority": 16,
	"AddTimestamp": 32,
	"LowPriority": 64,

	// Value-to-name mapping for convenience
	"0": "Error",
	"1": "File",
	"2": "Parts",
	"4": "Compressed",
	"7": "AllMask",
	"8": "IsJob",
	"16": "HighPriority",
	"32": "AddTimestamp",
	"64": "LowPriority",
};

module.exports = EDRMBlobDownloadType;
