/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EExternalAccountType = {
	"k_EExternalNone": 0,
	"k_EExternalSteamAccount": 1,
	"k_EExternalGoogleAccount": 2,
	"k_EExternalFacebookAccount": 3,
	"k_EExternalTwitterAccount": 4,
	"k_EExternalTwitchAccount": 5,
	"k_EExternalYouTubeChannelAccount": 6,
	"k_EExternalFacebookPage": 7,

	// Value-to-name mapping for convenience
	"0": "k_EExternalNone",
	"1": "k_EExternalSteamAccount",
	"2": "k_EExternalGoogleAccount",
	"3": "k_EExternalFacebookAccount",
	"4": "k_EExternalTwitterAccount",
	"5": "k_EExternalTwitchAccount",
	"6": "k_EExternalYouTubeChannelAccount",
	"7": "k_EExternalFacebookPage",
};

module.exports = EExternalAccountType;
