/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EGameSearchAction = {
	"None": 0,
	"Accept": 1,
	"Decline": 2,
	"Cancel": 3,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Accept",
	"2": "Decline",
	"3": "Cancel",
};

module.exports = EGameSearchAction;
