/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EGetGamesAlgorithm = {
	"Default": 1,
	"MostPlayed": 2,
	"PopularNew": 3,

	// Value-to-name mapping for convenience
	"1": "Default",
	"2": "MostPlayed",
	"3": "PopularNew",
};

module.exports = EGetGamesAlgorithm;
