/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EGetChannelsAlgorithm = {
	"Default": 1,
	"Friends": 2,
	"Featured": 3,
	"Developer": 4,
	"Following": 5,

	// Value-to-name mapping for convenience
	"1": "Default",
	"2": "Friends",
	"3": "Featured",
	"4": "Developer",
	"5": "Following",
};

module.exports = EGetChannelsAlgorithm;
