/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EGPUPerformanceLevel = {
	"Invalid": 0,
	"Auto": 1,
	"Manual": 2,
	"Low": 3,
	"High": 4,
	"Profiling": 5,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Auto",
	"2": "Manual",
	"3": "Low",
	"4": "High",
	"5": "Profiling",
};

module.exports = EGPUPerformanceLevel;
