/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EGraphicsPerfOverlayLevel = {
	"Hidden": 0,
	"Basic": 1,
	"Medium": 2,
	"Full": 3,
	"Minimal": 4,

	// Value-to-name mapping for convenience
	"0": "Hidden",
	"1": "Basic",
	"2": "Medium",
	"3": "Full",
	"4": "Minimal",
};

module.exports = EGraphicsPerfOverlayLevel;
