/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EHDRToneMapOperator = {
	"Invalid": 0,
	"Uncharted": 1,
	"Reinhard": 2,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Uncharted",
	"2": "Reinhard",
};

module.exports = EHDRToneMapOperator;
