/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EHIDDeviceLocation = {
	"Local": 0,
	"Remote": 2,
	"Any": 3,

	// Value-to-name mapping for convenience
	"0": "Local",
	"2": "Remote",
	"3": "Any",
};

module.exports = EHIDDeviceLocation;
