/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EHIDDeviceDisconnectMethod = {
	"Unknown": 0,
	"Bluetooth": 1,
	"FeatureReport": 2,
	"OutputReport": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Bluetooth",
	"2": "FeatureReport",
	"3": "OutputReport",
};

module.exports = EHIDDeviceDisconnectMethod;
