/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EInputMode = {
	"Unknown": 0,
	"Mouse": 1,
	"Controller": 2,
	"MouseAndController": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Mouse",
	"2": "Controller",
	"3": "MouseAndController",
};

module.exports = EInputMode;
