/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EIntroducerRouting = {
	"FileShare": 0, // removed
	"P2PVoiceChat": 1,
	"P2PNetworking": 2,

	// Value-to-name mapping for convenience
	"0": "FileShare",
	"1": "P2PVoiceChat",
	"2": "P2PNetworking",
};

module.exports = EIntroducerRouting;
