/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EInternalAccountType = {
	"k_EInternalSteamAccountType": 1,
	"k_EInternalClanType": 2,
	"k_EInternalAppType": 3,
	"k_EInternalBroadcastChannelType": 4,

	// Value-to-name mapping for convenience
	"1": "k_EInternalSteamAccountType",
	"2": "k_EInternalClanType",
	"3": "k_EInternalAppType",
	"4": "k_EInternalBroadcastChannelType",
};

module.exports = EInternalAccountType;
