/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EJSRegisterMethodType = {
	"Invalid": 0,
	"Function": 1,
	"Callback": 2,
	"Promise": 3,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Function",
	"2": "Callback",
	"3": "Promise",
};

module.exports = EJSRegisterMethodType;
