/* eslint-disable */
// Auto-generated by generate-enums script on Mon Sep 02 2024 23:48:07 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ELauncherType = {
	"Default": 0,
	"PerfectWorld": 1,
	"Nexon": 2,
	"CmdLine": 3,
	"CSGO": 4,
	"ClientUI": 5,
	"Headless": 6,
	"SteamChina": 7,
	"SingleApp": 8,
	"GameServer": 9,

	// Value-to-name mapping for convenience
	"0": "Default",
	"1": "PerfectWorld",
	"2": "Nexon",
	"3": "CmdLine",
	"4": "CSGO",
	"5": "ClientUI",
	"6": "Headless",
	"7": "SteamChina",
	"8": "SingleApp",
	"9": "GameServer",
};

module.exports = ELauncherType;
