/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELeaderboardDataRequest = {
	"Global": 0,
	"GlobalAroundUser": 1,
	"Friends": 2,
	"Users": 3,

	// Value-to-name mapping for convenience
	"0": "Global",
	"1": "GlobalAroundUser",
	"2": "Friends",
	"3": "Users",
};

module.exports = ELeaderboardDataRequest;
