/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELeaderboardSortMethod = {
	"None": 0,
	"Ascending": 1,
	"Descending": 2,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Ascending",
	"2": "Descending",
};

module.exports = ELeaderboardSortMethod;
