/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELeaderboardDisplayType = {
	"None": 0,
	"Numeric": 1,
	"TimeSeconds": 2,
	"TimeMilliSeconds": 3,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Numeric",
	"2": "TimeSeconds",
	"3": "TimeMilliSeconds",
};

module.exports = ELeaderboardDisplayType;
