/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELeaderboardUploadScoreMethod = {
	"None": 0,
	"KeepBest": 1,
	"ForceUpdate": 2,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "KeepBest",
	"2": "ForceUpdate",
};

module.exports = ELeaderboardUploadScoreMethod;
