/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELicenseType = {
	"NoLicense": 0,
	"SinglePurchase": 1,
	"SinglePurchaseLimitedUse": 2,
	"RecurringCharge": 3,
	"RecurringChargeLimitedUse": 4,
	"RecurringChargeLimitedUseWithOverages": 5,
	"RecurringOption": 6,
	"LimitedUseDelayedActivation": 7,

	// Value-to-name mapping for convenience
	"0": "NoLicense",
	"1": "SinglePurchase",
	"2": "SinglePurchaseLimitedUse",
	"3": "RecurringCharge",
	"4": "RecurringChargeLimitedUse",
	"5": "RecurringChargeLimitedUseWithOverages",
	"6": "RecurringOption",
	"7": "LimitedUseDelayedActivation",
};

module.exports = ELicenseType;
