/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELobbyType = {
	"Private": 0,
	"FriendsOnly": 1,
	"Public": 2,
	"Invisible": 3,
	"PrivateUnique": 4,

	// Value-to-name mapping for convenience
	"0": "Private",
	"1": "FriendsOnly",
	"2": "Public",
	"3": "Invisible",
	"4": "PrivateUnique",
};

module.exports = ELobbyType;
