/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELobbyComparison = {
	"EqualToOrLessThan": -2,
	"LessThan": -1,
	"Equal": 0,
	"GreaterThan": 1,
	"EqualToOrGreaterThan": 2,
	"NotEqual": 3,

	// Value-to-name mapping for convenience
	"-2": "EqualToOrLessThan",
	"-1": "LessThan",
	"0": "Equal",
	"1": "GreaterThan",
	"2": "EqualToOrGreaterThan",
	"3": "NotEqual",
};

module.exports = ELobbyComparison;
