/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ELobbyFilterType = {
	"String": 0,
	"Numerical": 1,
	"SlotsAvailable": 2,
	"NearValue": 3,
	"Distance": 4,

	// Value-to-name mapping for convenience
	"0": "String",
	"1": "Numerical",
	"2": "SlotsAvailable",
	"3": "NearValue",
	"4": "Distance",
};

module.exports = ELobbyFilterType;
