/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:13:56 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EMarketingMessageLookupType = {
	"Invalid": 0,
	"ByGID": 1,
	"Active": 2,
	"ByTitleWithType": 3,
	"ByGIDList": 4,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "ByGID",
	"2": "Active",
	"3": "ByTitleWithType",
	"4": "ByGIDList",
};

module.exports = EMarketingMessageLookupType;
