/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:13:56 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EMarketingMessageVisibility = {
	"Beta": 1,
	"Public": 2,

	// Value-to-name mapping for convenience
	"1": "Beta",
	"2": "Public",
};

module.exports = EMarketingMessageVisibility;
