/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EMarketingMessageFlags = {
	"None": 0,
	"HighPriority": 1,
	"PlatformWindows": 2,
	"PlatformMac": 4,
	"PlatformLinux": 8,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "HighPriority",
	"2": "PlatformWindows",
	"4": "PlatformMac",
	"8": "PlatformLinux",
};

module.exports = EMarketingMessageFlags;

module.exports.PlatformRestrictions = module.exports.PlatformWindows | module.exports.PlatformMac | module.exports.PlatformLinux;
