/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:13:56 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EMarketingMessageAssociationType = {
	"NoAssociation": 0,
	"AppAssociation": 1,
	"SubscriptionAssociation": 2,
	"PublisherAssociation": 3,
	"GenreAssociation": 4,
	"BundleAssociation": 5,

	// Value-to-name mapping for convenience
	"0": "NoAssociation",
	"1": "AppAssociation",
	"2": "SubscriptionAssociation",
	"3": "PublisherAssociation",
	"4": "GenreAssociation",
	"5": "BundleAssociation",
};

module.exports = EMarketingMessageAssociationType;
