/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:13:56 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EMarketingMessageType = {
	"Invalid": 0,
	"NowAvailable": 1,
	"WeekendDeal": 2,
	"PrePurchase": 3,
	"PlayNow": 4,
	"PreloadNow": 5,
	"General": 6,
	"DemoQuit": 7,
	"Gifting": 8,
	"EJsKorner": 9,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "NowAvailable",
	"2": "WeekendDeal",
	"3": "PrePurchase",
	"4": "PlayNow",
	"5": "PreloadNow",
	"6": "General",
	"7": "DemoQuit",
	"8": "Gifting",
	"9": "EJsKorner",
};

module.exports = EMarketingMessageType;
