/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EMouseMode = {
	"Unknown": 0,
	"RelativeCursor": 1,
	"AbsoluteCursor": 2,
	"Touch": 3,
	"Relative": 4,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "RelativeCursor",
	"2": "AbsoluteCursor",
	"3": "Touch",
	"4": "Relative",
};

module.exports = EMouseMode;
