/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ENewsUpdateType = {
	"AppNews": 0,
	"SteamAds": 1,
	"SteamNews": 2,
	"CDDBUpdate": 3,
	"ClientUpdate": 4,

	// Value-to-name mapping for convenience
	"0": "AppNews",
	"1": "SteamAds",
	"2": "SteamNews",
	"3": "CDDBUpdate",
	"4": "ClientUpdate",
};

module.exports = ENewsUpdateType;
