/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ENewSteamAnnouncementState = {
	"Invalid": 0,
	"AllRead": 1,
	"NewAnnouncement": 2,
	"FeaturedAnnouncement": 3,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "AllRead",
	"2": "NewAnnouncement",
	"3": "FeaturedAnnouncement",
};

module.exports = ENewSteamAnnouncementState;
