/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ENotificationSetting = {
	"NotifyUseDefault": 0,
	"Always": 1,
	"Never": 2,

	// Value-to-name mapping for convenience
	"0": "NotifyUseDefault",
	"1": "Always",
	"2": "Never",
};

module.exports = ENotificationSetting;
