/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EOSBranch = {
	"Unknown": 0,
	"Release": 1,
	"ReleaseCandidate": 2,
	"Beta": 3,
	"BetaCandidate": 4,
	"Main": 5,
	"Staging": 6,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Release",
	"2": "ReleaseCandidate",
	"3": "Beta",
	"4": "BetaCandidate",
	"5": "Main",
	"6": "Staging",
};

module.exports = EOSBranch;
