/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPackageStatus = {
	"Available": 0,
	"Preorder": 1,
	"Unavailable": 2,
	"Invalid": 3,

	// Value-to-name mapping for convenience
	"0": "Available",
	"1": "Preorder",
	"2": "Unavailable",
	"3": "Invalid",
};

module.exports = EPackageStatus;
