/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPlatformType = {
	"Unknown": 0,
	"Win32": 1,
	"Win64": 2,
	"Linux": 3, // removed "split to Linux64 and Linux32"
	"Linux64": 3,
	"OSX": 4,
	"PS3": 5,
	"Linux32": 6,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Win32",
	"2": "Win64",
	"3": "Linux64",
	"4": "OSX",
	"5": "PS3",
	"6": "Linux32",
};

module.exports = EPlatformType;
