/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EPlaytestStatus = {
	"None": 0,
	"Pending": 1,
	"Invited": 2,
	"Granted": 3,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Pending",
	"2": "Invited",
	"3": "Granted",
};

module.exports = EPlaytestStatus;
