/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:33:23 GMT-0500 (Eastern Standard Time)

/**
 * @enum EProtoAppType
 * @readonly
 */
const EProtoAppType = {
	"k_EAppTypeDepotOnly": -2147483648, // obsolete
	"DepotOnly": -2147483648,
	"k_EAppTypeInvalid": 0, // obsolete
	"Invalid": 0,
	"k_EAppTypeGame": 1, // obsolete
	"Game": 1,
	"k_EAppTypeApplication": 2, // obsolete
	"Application": 2,
	"k_EAppTypeTool": 4, // obsolete
	"Tool": 4,
	"k_EAppTypeDemo": 8, // obsolete
	"Demo": 8,
	"k_EAppTypeDeprected": 16, // obsolete
	"Deprected": 16,
	"k_EAppTypeDLC": 32, // obsolete
	"DLC": 32,
	"k_EAppTypeGuide": 64, // obsolete
	"Guide": 64,
	"k_EAppTypeDriver": 128, // obsolete
	"Driver": 128,
	"k_EAppTypeConfig": 256, // obsolete
	"Config": 256,
	"k_EAppTypeHardware": 512, // obsolete
	"Hardware": 512,
	"k_EAppTypeFranchise": 1024, // obsolete
	"Franchise": 1024,
	"k_EAppTypeVideo": 2048, // obsolete
	"Video": 2048,
	"k_EAppTypePlugin": 4096, // obsolete
	"Plugin": 4096,
	"k_EAppTypeMusicAlbum": 8192, // obsolete
	"MusicAlbum": 8192,
	"k_EAppTypeSeries": 16384, // obsolete
	"Series": 16384,
	"k_EAppTypeComic": 32768, // obsolete
	"Comic": 32768,
	"k_EAppTypeBeta": 65536, // obsolete
	"Beta": 65536,
	"k_EAppTypeShortcut": 1073741824, // obsolete
	"Shortcut": 1073741824,

	// Value-to-name mapping for convenience
	"-2147483648": "DepotOnly",
	"0": "Invalid",
	"1": "Game",
	"2": "Application",
	"4": "Tool",
	"8": "Demo",
	"16": "Deprected",
	"32": "DLC",
	"64": "Guide",
	"128": "Driver",
	"256": "Config",
	"512": "Hardware",
	"1024": "Franchise",
	"2048": "Video",
	"4096": "Plugin",
	"8192": "MusicAlbum",
	"16384": "Series",
	"32768": "Comic",
	"65536": "Beta",
	"1073741824": "Shortcut",
};

module.exports = EProtoAppType;
