/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EProvideDeckFeedbackPreference = {
	"Unset": 0,
	"Yes": 1,
	"No": 2,

	// Value-to-name mapping for convenience
	"0": "Unset",
	"1": "Yes",
	"2": "No",
};

module.exports = EProvideDeckFeedbackPreference;
