/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EProtoExecutionSite = {
	"Unknown": 0,
	"SteamClient": 2,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"2": "SteamClient",
};

module.exports = EProtoExecutionSite;
