/* eslint-disable */
// Auto-generated by generate-enums script on Mon Sep 02 2024 23:48:07 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EPublishedFileVisibility = {
	"Public": 0,
	"FriendsOnly": 1,
	"Private": 2,
	"Unlisted": 3,

	// Value-to-name mapping for convenience
	"0": "Public",
	"1": "FriendsOnly",
	"2": "Private",
	"3": "Unlisted",
};

module.exports = EPublishedFileVisibility;
