/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPublishedFileVisibility = {
	"Public": 0,
	"FriendsOnly": 1,
	"Private": 2,

	// Value-to-name mapping for convenience
	"0": "Public",
	"1": "FriendsOnly",
	"2": "Private",
};

module.exports = EPublishedFileVisibility;
