/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPublishedFileInappropriateResult = {
	"NotScanned": 0,
	"VeryUnlikely": 1,
	"Unlikely": 30,
	"Possible": 50,
	"Likely": 75,
	"VeryLikely": 100,

	// Value-to-name mapping for convenience
	"0": "NotScanned",
	"1": "VeryUnlikely",
	"30": "Unlikely",
	"50": "Possible",
	"75": "Likely",
	"100": "VeryLikely",
};

module.exports = EPublishedFileInappropriateResult;
