/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPublishedFileInappropriateProvider = {
	"Invalid": 0,
	"Google": 1,
	"Amazon": 2,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Google",
	"2": "Amazon",
};

module.exports = EPublishedFileInappropriateProvider;
