/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPublishedFileForSaleStatus = {
	"NotForSale": 0,
	"PendingApproval": 1,
	"ApprovedForSale": 2,
	"RejectedForSale": 3,
	"NoLongerForSale": 4,
	"TentativeApproval": 5,

	// Value-to-name mapping for convenience
	"0": "NotForSale",
	"1": "PendingApproval",
	"2": "ApprovedForSale",
	"3": "RejectedForSale",
	"4": "NoLongerForSale",
	"5": "TentativeApproval",
};

module.exports = EPublishedFileForSaleStatus;
