/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EPublishedFileRevision = {
	"Default": 0,
	"Latest": 1,
	"ApprovedSnapshot": 2,
	"ApprovedSnapshot_China": 3,
	"RejectedSnapshot": 4,
	"RejectedSnapshot_China": 5,

	// Value-to-name mapping for convenience
	"0": "Default",
	"1": "Latest",
	"2": "ApprovedSnapshot",
	"3": "ApprovedSnapshot_China",
	"4": "RejectedSnapshot",
	"5": "RejectedSnapshot_China",
};

module.exports = EPublishedFileRevision;
