/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ERemoteClientService = {
	"None": 0,
	"RemoteControl": 1,
	"GameStreaming": 2,
	"SiteLicense": 4,
	"ContentCache": 8,
	"ContentServer": 16,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "RemoteControl",
	"2": "GameStreaming",
	"4": "SiteLicense",
	"8": "ContentCache",
	"16": "ContentServer",
};

module.exports = ERemoteClientService;
