/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ERemoteClientService = {
	"None": 0,
	"RemoteControl": 1,
	"GameStreaming": 2,
	"SiteLicense": 4,
	"ContentCache": 8,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "RemoteControl",
	"2": "GameStreaming",
	"4": "SiteLicense",
	"8": "ContentCache",
};

module.exports = ERemoteClientService;
