/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ERemoteDeviceStreamingResult = {
	"Success": 0,
	"Unauthorized": 1,
	"ScreenLocked": 2,
	"Failed": 3,
	"Busy": 4,
	"InProgress": 5,
	"Canceled": 6,
	"DriversNotInstalled": 7,
	"Disabled": 8,
	"BroadcastingActive": 9,
	"VRActive": 10,
	"PINRequired": 11,
	"TransportUnavailable": 12,
	"Invisible": 13,
	"GameLaunchFailed": 14,

	// Value-to-name mapping for convenience
	"0": "Success",
	"1": "Unauthorized",
	"2": "ScreenLocked",
	"3": "Failed",
	"4": "Busy",
	"5": "InProgress",
	"6": "Canceled",
	"7": "DriversNotInstalled",
	"8": "Disabled",
	"9": "BroadcastingActive",
	"10": "VRActive",
	"11": "PINRequired",
	"12": "TransportUnavailable",
	"13": "Invisible",
	"14": "GameLaunchFailed",
};

module.exports = ERemoteDeviceStreamingResult;
