/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EScalingFilter = {
	"Invalid": 0,
	"FSR": 1,
	"Nearest": 2,
	"Integer": 3,
	"Linear": 4,
	"NIS": 5,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "FSR",
	"2": "Nearest",
	"3": "Integer",
	"4": "Linear",
	"5": "NIS",
};

module.exports = EScalingFilter;
