/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESDCardFormatStage = {
	"Invalid": 0,
	"Starting": 1,
	"Testing": 2,
	"Rescuing": 3,
	"Formatting": 4,
	"Finalizing": 5,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Starting",
	"2": "Testing",
	"3": "Rescuing",
	"4": "Formatting",
	"5": "Finalizing",
};

module.exports = ESDCardFormatStage;
