/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EServerFlags = {
	"None": 0,
	"Active": 1,
	"Secure": 2,
	"Dedicated": 4,
	"Linux": 8,
	"Passworded": 16,
	"Private": 32,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Active",
	"2": "Secure",
	"4": "Dedicated",
	"8": "Linux",
	"16": "Passworded",
	"32": "Private",
};

module.exports = EServerFlags;
