/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESessionPersistence = {
	"Invalid": -1,
	"Ephemeral": 0,
	"Persistent": 1,

	// Value-to-name mapping for convenience
	"-1": "Invalid",
	"0": "Ephemeral",
	"1": "Persistent",
};

module.exports = ESessionPersistence;
