/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESplitScalingFilter = {
	"Invalid": 0,
	"Linear": 1,
	"Nearest": 2,
	"FSR": 3,
	"NIS": 4,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Linear",
	"2": "Nearest",
	"3": "FSR",
	"4": "NIS",
};

module.exports = ESplitScalingFilter;
