/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESplitScalingScaler = {
	"Invalid": 0,
	"Auto": 1,
	"Integer": 2,
	"Fit": 3,
	"Fill": 4,
	"Stretch": 5,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Auto",
	"2": "Integer",
	"3": "Fit",
	"4": "Fill",
	"5": "Stretch",
};

module.exports = ESplitScalingScaler;
