/* eslint-disable */
// Auto-generated by generate-enums script on Tue Sep 03 2024 00:00:33 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESteamNotificationType = {
	Invalid: 0,
	Test: 1,
	Gift: 2,
	Comment: 3,
	Item: 4,
	FriendInvite: 5,
	MajorSale: 6,
	PreloadAvailable: 7,
	Wishlist: 8,
	TradeOffer: 9,
	General: 10,
	HelpRequest: 11,
	AsyncGame: 12,
	ChatMsg: 13,
	ModeratorMsg: 14,
	ParentalFeatureAccessRequest: 15,
	FamilyInvite: 16,
	FamilyPurchaseRequest: 17,
	ParentalPlaytimeRequest: 18,
	FamilyPurchaseRequestResponse: 19,
	ParentalFeatureAccessResponse: 20,
	ParentalPlaytimeResponse: 21,
	RequestedGameAdded: 22,
	SendToPhone: 23,
	ClipDownloaded: 24,
	TwoFactorPrompt: 25,
	MobileConfirmation: 26,
	PartnerEvent: 27,

	// Value-to-name mapping for convenience
	0: 'Invalid',
	1: 'Test',
	2: 'Gift',
	3: 'Comment',
	4: 'Item',
	5: 'FriendInvite',
	6: 'MajorSale',
	7: 'PreloadAvailable',
	8: 'Wishlist',
	9: 'TradeOffer',
	10: 'General',
	11: 'HelpRequest',
	12: 'AsyncGame',
	13: 'ChatMsg',
	14: 'ModeratorMsg',
	15: 'ParentalFeatureAccessRequest',
	16: 'FamilyInvite',
	17: 'FamilyPurchaseRequest',
	18: 'ParentalPlaytimeRequest',
	19: 'FamilyPurchaseRequestResponse',
	20: 'ParentalFeatureAccessResponse',
	21: 'ParentalPlaytimeResponse',
	22: 'RequestedGameAdded',
	23: 'SendToPhone',
	24: 'ClipDownloaded',
	25: 'TwoFactorPrompt',
	26: 'MobileConfirmation',
	27: 'PartnerEvent',
};

module.exports = ESteamNotificationType;
