/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ESteamNetworkingUDPMsgID = {
	"ChallengeRequest": 32,
	"ChallengeReply": 33,
	"ConnectRequest": 34,
	"ConnectOK": 35,
	"ConnectionClosed": 36,
	"NoConnection": 37,

	// Value-to-name mapping for convenience
	"32": "ChallengeRequest",
	"33": "ChallengeReply",
	"34": "ConnectRequest",
	"35": "ConnectOK",
	"36": "ConnectionClosed",
	"37": "NoConnection",
};

module.exports = ESteamNetworkingUDPMsgID;
