/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ESteamNetworkingSocketsCipher = {
	"INVALID": 0,
	"NULL": 1,
	"AES_256_GCM": 2,

	// Value-to-name mapping for convenience
	"0": "INVALID",
	"1": "NULL",
	"2": "AES_256_GCM",
};

module.exports = ESteamNetworkingSocketsCipher;
