/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ESteamPipeWorkType = {
	"Invalid": 0,
	"StageFromChunkStores": 1,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "StageFromChunkStores",
};

module.exports = ESteamPipeWorkType;
