/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ESteamPipeOperationType = {
	"Invalid": 0,
	"DecryptCPU": 1,
	"DiskRead": 2,
	"DiskWrite": 3,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "DecryptCPU",
	"2": "DiskRead",
	"3": "DiskWrite",
};

module.exports = ESteamPipeOperationType;
