/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESteamDeckCompatibilityCategory = {
	"Unknown": 0,
	"Unsupported": 1,
	"Playable": 2,
	"Verified": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Unsupported",
	"2": "Playable",
	"3": "Verified",
};

module.exports = ESteamDeckCompatibilityCategory;
