/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESteamTVContentTemplate = {
	"Invalid": 0,
	"Takeover": 1,
	"SingleGame": 2,
	"GameList": 3,
	"QuickExplore": 4,
	"ConveyorBelt": 5,
	"WatchParty": 6,
	"Developer": 7,
	"Event": 8,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Takeover",
	"2": "SingleGame",
	"3": "GameList",
	"4": "QuickExplore",
	"5": "ConveyorBelt",
	"6": "WatchParty",
	"7": "Developer",
	"8": "Event",
};

module.exports = ESteamTVContentTemplate;
