/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ESteamReviewScore = {
	"None": 0,
	"OverwhelminglyNegative": 1,
	"VeryNegative": 2,
	"Negative": 3,
	"MostlyNegative": 4,
	"Mixed": 5,
	"MostlyPositive": 6,
	"Positive": 7,
	"VeryPositive": 8,
	"OverwhelminglyPositive": 9,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "OverwhelminglyNegative",
	"2": "VeryNegative",
	"3": "Negative",
	"4": "MostlyNegative",
	"5": "Mixed",
	"6": "MostlyPositive",
	"7": "Positive",
	"8": "VeryPositive",
	"9": "OverwhelminglyPositive",
};

module.exports = ESteamReviewScore;
