/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESteamDeckCompatibilityFeedback = {
	"Unset": 0,
	"Agree": 1,
	"Disagree": 2,
	"Ignore": 3,

	// Value-to-name mapping for convenience
	"0": "Unset",
	"1": "Agree",
	"2": "Disagree",
	"3": "Ignore",
};

module.exports = ESteamDeckCompatibilityFeedback;
