/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESteamDeckCompatibilityResultDisplayType = {
	"Invisible": 0,
	"Informational": 1,
	"Unsupported": 2,
	"Playable": 3,
	"Verified": 4,

	// Value-to-name mapping for convenience
	"0": "Invisible",
	"1": "Informational",
	"2": "Unsupported",
	"3": "Playable",
	"4": "Verified",
};

module.exports = ESteamDeckCompatibilityResultDisplayType;
