/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStoreDiscoveryQueueType = {
	"New": 0,
	"ComingSoon": 1,
	"Recommended": 2,
	"EveryNewRelease": 3,
	"MLRecommender": 5,
	"WishlistOnSale": 6,
	"DLC": 7,
	"DLCOnSale": 8,
	"RecommendedComingSoon": 9,
	"RecommendedFree": 10,
	"RecommendedOnSale": 11,
	"RecommendedDemos": 12,
	"DLCNewReleases": 13,
	"DLCTopSellers": 14,
	"MAX": 15,

	// Value-to-name mapping for convenience
	"0": "New",
	"1": "ComingSoon",
	"2": "Recommended",
	"3": "EveryNewRelease",
	"5": "MLRecommender",
	"6": "WishlistOnSale",
	"7": "DLC",
	"8": "DLCOnSale",
	"9": "RecommendedComingSoon",
	"10": "RecommendedFree",
	"11": "RecommendedOnSale",
	"12": "RecommendedDemos",
	"13": "DLCNewReleases",
	"14": "DLCTopSellers",
	"15": "MAX",
};

module.exports = EStoreDiscoveryQueueType;
