/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStoreCategoryType = {
	"Category": 0,
	"SupportedPlayers": 1,
	"Feature": 2,
	"ControllerSupport": 3,
	"CloudGaming": 4,
	"MAX": 5,

	// Value-to-name mapping for convenience
	"0": "Category",
	"1": "SupportedPlayers",
	"2": "Feature",
	"3": "ControllerSupport",
	"4": "CloudGaming",
	"5": "MAX",
};

module.exports = EStoreCategoryType;
