/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStoreAppType = {
	"Game": 0,
	"Demo": 1,
	"Mod": 2,
	"Movie": 3,
	"DLC": 4,
	"Guide": 5,
	"Software": 6,
	"Video": 7,
	"Series": 8,
	"Episode": 9,
	"Hardware": 10,
	"Music": 11,
	"Beta": 12,
	"Tool": 13,
	"Advertising": 14,

	// Value-to-name mapping for convenience
	"0": "Game",
	"1": "Demo",
	"2": "Mod",
	"3": "Movie",
	"4": "DLC",
	"5": "Guide",
	"6": "Software",
	"7": "Video",
	"8": "Series",
	"9": "Episode",
	"10": "Hardware",
	"11": "Music",
	"12": "Beta",
	"13": "Tool",
	"14": "Advertising",
};

module.exports = EStoreAppType;
