/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStorageDriveMediaType = {
	"Invalid": 0,
	"Unknown": 1,
	"HDD": 2,
	"SSD": 3,
	"Removable": 4,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Unknown",
	"2": "HDD",
	"3": "SSD",
	"4": "Removable",
};

module.exports = EStorageDriveMediaType;
