/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStoreItemType = {
	"Invalid": -1,
	"App": 0,
	"Package": 1,
	"Bundle": 2,
	"Mtx": 3,
	"Tag": 4,
	"Creator": 5,

	// Value-to-name mapping for convenience
	"-1": "Invalid",
	"0": "App",
	"1": "Package",
	"2": "Bundle",
	"3": "Mtx",
	"4": "Tag",
	"5": "Creator",
};

module.exports = EStoreItemType;
