/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamChannel = {
	"Invalid": -1,
	"Discovery": 0,
	"Control": 1,
	"Stats": 2,
	"DataChannelStart": 3,

	// Value-to-name mapping for convenience
	"-1": "Invalid",
	"0": "Discovery",
	"1": "Control",
	"2": "Stats",
	"3": "DataChannelStart",
};

module.exports = EStreamChannel;
