/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamingDataType = {
	"AudioData": 0,
	"VideoData": 1,
	"MicrophoneData": 2,

	// Value-to-name mapping for convenience
	"0": "AudioData",
	"1": "VideoData",
	"2": "MicrophoneData",
};

module.exports = EStreamingDataType;
