/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamDeviceFormFactor = {
	"Unknown": 0,
	"Phone": 1,
	"Tablet": 2,
	"Computer": 3,
	"TV": 4,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "Phone",
	"2": "Tablet",
	"3": "Computer",
	"4": "TV",
};

module.exports = EStreamDeviceFormFactor;
