/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStreamingDataType = {
	"AudioData": 0,
	"VideoData": 1,
	"MicrophoneData": 2,
	"NeptuneData": 3,

	// Value-to-name mapping for convenience
	"0": "AudioData",
	"1": "VideoData",
	"2": "MicrophoneData",
	"3": "NeptuneData",
};

module.exports = EStreamingDataType;
