/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStreamControllerConfigMsg = {
	"RequestConfigsForApp": 0,
	"ConfigResponse": 1,
	"PersonalizationResponse": 2,
	"ActiveConfigChange": 3,
	"RequestActiveConfig": 4,

	// Value-to-name mapping for convenience
	"0": "RequestConfigsForApp",
	"1": "ConfigResponse",
	"2": "PersonalizationResponse",
	"3": "ActiveConfigChange",
	"4": "RequestActiveConfig",
};

module.exports = EStreamControllerConfigMsg;
