/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamStatsMessage = {
	"FrameEvents": 1,
	"DebugDump": 2,
	"LogMessage": 3,
	"LogUploadBegin": 4,
	"LogUploadData": 5,
	"LogUploadComplete": 6,

	// Value-to-name mapping for convenience
	"1": "FrameEvents",
	"2": "DebugDump",
	"3": "LogMessage",
	"4": "LogUploadBegin",
	"5": "LogUploadData",
	"6": "LogUploadComplete",
};

module.exports = EStreamStatsMessage;
