/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:33:23 GMT-0500 (Eastern Standard Time)

/**
 * @enum EStreamQualityPreference
 * @readonly
 */
const EStreamQualityPreference = {
	"Automatic": -1,
	"Fast": 1,
	"Balanced": 2,
	"Beautiful": 3,

	// Value-to-name mapping for convenience
	"-1": "Automatic",
	"1": "Fast",
	"2": "Balanced",
	"3": "Beautiful",
};

module.exports = EStreamQualityPreference;
