/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EStreamColorspace = {
	"Unknown": 0,
	"BT601": 1,
	"BT601_Full": 2,
	"BT709": 3,
	"BT709_Full": 4,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "BT601",
	"2": "BT601_Full",
	"3": "BT709",
	"4": "BT709_Full",
};

module.exports = EStreamColorspace;
