/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamMouseWheelDirection = {
	"Down": -120,
	"Left": 3,
	"Right": 4,
	"Up": 120,

	// Value-to-name mapping for convenience
	"-120": "Down",
	"3": "Left",
	"4": "Right",
	"120": "Up",
};

module.exports = EStreamMouseWheelDirection;
