/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamVideoCodec = {
	"None": 0,
	"Raw": 1,
	"VP8": 2,
	"VP9": 3,
	"H264": 4,
	"HEVC": 5,
	"ORBX1": 6,
	"ORBX2": 7,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Raw",
	"2": "VP8",
	"3": "VP9",
	"4": "H264",
	"5": "HEVC",
	"6": "ORBX1",
	"7": "ORBX2",
};

module.exports = EStreamVideoCodec;
