/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamTransport = {
	"None": 0,
	"UDP": 1,
	"UDPRelay": 2,
	"WebRTC": 3,
	"SDR": 4,
	"UDP_SNS": 5,
	"SNS": 6, // obsolete
	"UDPRelay_SNS": 6,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "UDP",
	"2": "UDPRelay",
	"3": "WebRTC",
	"4": "SDR",
	"5": "UDP_SNS",
	"6": "UDPRelay_SNS",
};

module.exports = EStreamTransport;
