/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamInterface = {
	"Default": 0,
	"RecentGames": 1,
	"BigPicture": 2,
	"Desktop": 3,

	// Value-to-name mapping for convenience
	"0": "Default",
	"1": "RecentGames",
	"2": "BigPicture",
	"3": "Desktop",
};

module.exports = EStreamInterface;
