/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamDataMessage = {
	"DataPacket": 1,
	"DataLost": 2,

	// Value-to-name mapping for convenience
	"1": "DataPacket",
	"2": "DataLost",
};

module.exports = EStreamDataMessage;
