/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:33:23 GMT-0500 (Eastern Standard Time)

/**
 * @enum EStreamActivity
 * @readonly
 */
const EStreamActivity = {
	"Idle": 1,
	"Game": 2,
	"Desktop": 3,
	"SecureDesktop": 4,
	"Music": 5,

	// Value-to-name mapping for convenience
	"1": "Idle",
	"2": "Game",
	"3": "Desktop",
	"4": "SecureDesktop",
	"5": "Music",
};

module.exports = EStreamActivity;
