/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EStreamBitrate = {
	"Autodetect": -1,
	"Unlimited": 0,

	// Value-to-name mapping for convenience
	"-1": "Autodetect",
	"0": "Unlimited",
};

module.exports = EStreamBitrate;
