/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:33:23 GMT-0500 (Eastern Standard Time)

/**
 * @enum EStreamP2PScope
 * @readonly
 */
const EStreamP2PScope = {
	"Unknown": 0, // obsolete
	"Automatic": 0,
	"Disabled": 1,
	"OnlyMe": 2,
	"Friends": 3,
	"Everyone": 4,

	// Value-to-name mapping for convenience
	"0": "Automatic",
	"1": "Disabled",
	"2": "OnlyMe",
	"3": "Friends",
	"4": "Everyone",
};

module.exports = EStreamP2PScope;
