/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESystemAudioChannel = {
	"Invalid": 0,
	"Aggregated": 1,
	"FrontLeft": 2,
	"FrontRight": 3,
	"LFE": 4,
	"BackLeft": 5,
	"BackRight": 6,
	"FrontCenter": 7,
	"Unknown": 8,
	"Mono": 9,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Aggregated",
	"2": "FrontLeft",
	"3": "FrontRight",
	"4": "LFE",
	"5": "BackLeft",
	"6": "BackRight",
	"7": "FrontCenter",
	"8": "Unknown",
	"9": "Mono",
};

module.exports = ESystemAudioChannel;
