/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESystemAudioDirection = {
	"Invalid": 0,
	"Input": 1,
	"Output": 2,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Input",
	"2": "Output",
};

module.exports = ESystemAudioDirection;
