/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:45 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESystemFanControlMode = {
	"Invalid": 0,
	"Disabled": 1,
	"Default": 2,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Disabled",
	"2": "Default",
};

module.exports = ESystemFanControlMode;
