/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESystemAudioPortType = {
	"Invalid": 0,
	"Unknown": 1,
	"Audio32f": 2,
	"Midi8b": 3,
	"Video32RGBA": 4,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Unknown",
	"2": "Audio32f",
	"3": "Midi8b",
	"4": "Video32RGBA",
};

module.exports = ESystemAudioPortType;
