/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ESystemServiceState = {
	"Unavailable": 0,
	"Disabled": 1,
	"Enabled": 2,

	// Value-to-name mapping for convenience
	"0": "Unavailable",
	"1": "Disabled",
	"2": "Enabled",
};

module.exports = ESystemServiceState;
