/* eslint-disable */
// Auto-generated by generate-enums script on Fri Jun 30 2023 01:09:35 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ETokenRenewalType = {
	"None": 0,
	"Allow": 1,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Allow",
};

module.exports = ETokenRenewalType;
