/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const ETouchGesture = {
	"None": 0,
	"Touch": 1,
	"Tap": 2,
	"DoubleTap": 3,
	"ShortPress": 4,
	"LongPress": 5,
	"LongTap": 6,
	"TwoFingerTap": 7,
	"TapCancelled": 8,
	"PinchBegin": 9,
	"PinchUpdate": 10,
	"PinchEnd": 11,
	"FlingStart": 12,
	"FlingCancelled": 13,

	// Value-to-name mapping for convenience
	"0": "None",
	"1": "Touch",
	"2": "Tap",
	"3": "DoubleTap",
	"4": "ShortPress",
	"5": "LongPress",
	"6": "LongTap",
	"7": "TwoFingerTap",
	"8": "TapCancelled",
	"9": "PinchBegin",
	"10": "PinchUpdate",
	"11": "PinchEnd",
	"12": "FlingStart",
	"13": "FlingCancelled",
};

module.exports = ETouchGesture;
