/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const ETradeOfferConfirmationMethod = {
	"Invalid": 0,
	"Email": 1,
	"MobileApp": 2,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Email",
	"2": "MobileApp",
};

module.exports = ETradeOfferConfirmationMethod;
