/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EUCMFilePrivacyState = {
	"Invalid": -1,
	"Private": 2,
	"FriendsOnly": 4,
	"Public": 8,

	// Value-to-name mapping for convenience
	"-1": "Invalid",
	"2": "Private",
	"4": "FriendsOnly",
	"8": "Public",
};

module.exports = EUCMFilePrivacyState;

module.exports.All = module.exports.Public | module.exports.FriendsOnly | module.exports.Private;
