/* eslint-disable */
// Auto-generated by generate-enums script on Mon Sep 02 2024 23:48:07 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EUCMFilePrivacyState = {
	"Invalid": -1,
	"Private": 2,
	"FriendsOnly": 4,
	"Public": 8,
	"Unlisted": 16,

	// Value-to-name mapping for convenience
	"-1": "Invalid",
	"2": "Private",
	"4": "FriendsOnly",
	"8": "Public",
	"16": "Unlisted",
};

module.exports = EUCMFilePrivacyState;

module.exports.All = module.exports.Public | module.exports.FriendsOnly | module.exports.Private | module.exports.Unlisted;
