/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EUniverse = {
	"Invalid": 0,
	"Public": 1,
	"Beta": 2,
	"Internal": 3,
	"Dev": 4,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Public",
	"2": "Beta",
	"3": "Internal",
	"4": "Dev",
};

module.exports = EUniverse;
