/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EUpdaterType = {
	"Invalid": 0,
	"Client": 1,
	"OS": 2,
	"BIOS": 3,
	"Aggregated": 4,
	"Test1": 5,
	"Test2": 6,
	"Dummy": 7,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"1": "Client",
	"2": "OS",
	"3": "BIOS",
	"4": "Aggregated",
	"5": "Test1",
	"6": "Test2",
	"7": "Dummy",
};

module.exports = EUpdaterType;
