/* eslint-disable */
// Auto-generated by generate-enums script on Sun Aug 28 2022 18:46:03 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EUpdaterState = {
	"Invalid": 0,
	"UpToDate": 2,
	"Checking": 3,
	"Available": 4,
	"Applying": 5,
	"ClientRestartPending": 6,
	"SystemRestartPending": 7,

	// Value-to-name mapping for convenience
	"0": "Invalid",
	"2": "UpToDate",
	"3": "Checking",
	"4": "Available",
	"5": "Applying",
	"6": "ClientRestartPending",
	"7": "SystemRestartPending",
};

module.exports = EUpdaterState;
