/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EUserReviewScorePreference = {
	"Unset": 0,
	"IncludeAll": 1,
	"ExcludeBombs": 2,

	// Value-to-name mapping for convenience
	"0": "Unset",
	"1": "IncludeAll",
	"2": "ExcludeBombs",
};

module.exports = EUserReviewScorePreference;
