/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EValveIndexComponent = {
	"Unknown": 0,
	"HMD": 1,
	"LeftKnuckle": 2,
	"RightKnuckle": 3,

	// Value-to-name mapping for convenience
	"0": "Unknown",
	"1": "HMD",
	"2": "LeftKnuckle",
	"3": "RightKnuckle",
};

module.exports = EValveIndexComponent;
