/* eslint-disable */
// Auto-generated by generate-enums script on Thu Feb 24 2022 03:38:38 GMT-0500 (Eastern Standard Time)

/**
 * @enum
 * @readonly
 */
const EWorkshopFileType = {
	"First": 0,
	"SteamworksAccessInvite": 13,
	"SteamVideo": 14,
	"GameManagedItem": 15,

	// Value-to-name mapping for convenience
	"0": "First",
	"13": "SteamworksAccessInvite",
	"14": "SteamVideo",
	"15": "GameManagedItem",
};

module.exports = EWorkshopFileType;
