/* eslint-disable */
// Auto-generated by generate-enums script on Mon Sep 02 2024 23:48:07 GMT-0400 (Eastern Daylight Time)

/**
 * @enum
 * @readonly
 */
const EWorkshopFileType = {
	"First": 0,
	"SteamworksAccessInvite": 13,
	"SteamVideo": 14,
	"GameManagedItem": 15,
	"Clip": 16,

	// Value-to-name mapping for convenience
	"0": "First",
	"13": "SteamworksAccessInvite",
	"14": "SteamVideo",
	"15": "GameManagedItem",
	"16": "Clip",
};

module.exports = EWorkshopFileType;
