/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum E_STAR_GlyphWriteResult {
	Success = 0,
	InvalidMessage = 1,
	InvalidJSON = 2,
	SQLError = 3,
}

export default E_STAR_GlyphWriteResult;
