/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EACState {
	Unknown = 0,
	Disconnected = 1,
	Connected = 2,
	ConnectedSlow = 3,
}

export default EACState;
