/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EActivationCodeClass {
	WonCDKey = 0,
	ValveCDKey = 1,
	Doom3CDKey = 2,
	DBLookup = 3,
	Steam2010Key = 4,
	Max = 5,
	Test = 2147483647,
	Invalid = 4294967295,
}

export default EActivationCodeClass;
