/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EAppCloudStatus {
	Invalid = 0,
	Disabled = 1,
	Unknown = 2,
	Synchronized = 3,
	Checking = 4,
	OutOfSync = 5,
	Uploading = 6,
	Downloading = 7,
	SyncFailed = 8,
	Conflict = 9,
	PendingElsewhere = 10,
}

export default EAppCloudStatus;
