/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EAppType {
	DepotOnly = -2147483648, // obsolete
	Invalid = 0,
	Game = 1,
	Application = 2,
	Tool = 4,
	Demo = 8,
	Deprected = 16,
	DLC = 32,
	Guide = 64,
	Driver = 128,
	Config = 256,
	Hardware = 512,
	Franchise = 1024,
	Video = 2048,
	Plugin = 4096,
	Music = 8192,
	Series = 16384,
	Comic = 32768,
	Beta = 65536,
	Shortcut = 1073741824,
}

export default EAppType;
