/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EAppUsageEvent {
	GameLaunch = 1,
	GameLaunchTrial = 2,
	Media = 3,
	PreloadStart = 4,
	PreloadFinish = 5,
	MarketingMessageView = 6,
	InGameAdViewed = 7,
	GameLaunchFreeWeekend = 8,
}

export default EAppUsageEvent;
