/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EAppAssociationType {
	Invalid = 0,
	Publisher = 1,
	Developer = 2,
	Franchise = 3,
}

export default EAppAssociationType;
