/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EAppInfoSection {
	Unknown = 0,
	All = 1,
	Common = 2,
	First = 2,
	Extended = 3,
	Config = 4,
	Stats = 5,
	Install = 6,
	Depots = 7,
	VAC = 8, // removed
	VAC_UNUSED = 8, // removed
	DRM = 9, // removed
	DRM_UNUSED = 9, // removed
	UFS = 10,
	OGG = 11,
	Items = 12, // removed
	ItemsUNUSED = 12, // removed
	Policies = 13,
	SysReqs = 14,
	Community = 15,
	Store = 16,
	Localization = 17,
	Broadcastgamedata = 18,
	Computed = 19,
	Albummetadata = 20,
}

export default EAppInfoSection;
