/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EAppGamepadGyroTrackpadSupportLevel {
	Unknown = -1,
	NoGamepad = 0,
	Gamepad = 1,
	Simultaneous = 2,
}

export default EAppGamepadGyroTrackpadSupportLevel;
