/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EAppControllerSupportLevel {
	None = 0,
	Partial = 1,
	Full = 2,
}

export default EAppControllerSupportLevel;
