/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EAudioFormat {
	None = 0,
	SixteenBitLittleEndian = 1,
	Float = 2,
}

export default EAudioFormat;
