/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EAudioFormat {
	None = 0,
	16BitLittleEndian = 1,
	Float = 2,
}

export default EAudioFormat;
