/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EAuthSessionResponse {
	OK = 0,
	UserNotConnectedToSteam = 1,
	NoLicenseOrExpired = 2,
	VACBanned = 3,
	LoggedInElseWhere = 4,
	VACCheckTimedOut = 5,
	AuthTicketCanceled = 6,
	AuthTicketInvalidAlreadyUsed = 7,
	AuthTicketInvalid = 8,
	PublisherIssuedBan = 9,
}

export default EAuthSessionResponse;
