/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EBanContentCheckResult {
	NotScanned = 0,
	Reset = 1,
	NeedsChecking = 2,
	VeryUnlikely = 5,
	Unlikely = 30,
	Possible = 50,
	Likely = 75,
	VeryLikely = 100,
}

export default EBanContentCheckResult;
