/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EBatteryState {
	Unknown = 0,
	Discharging = 1,
	Charging = 2,
	Full = 3,
}

export default EBatteryState;
