/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EBillingType {
	NoCost = 0,
	BillOnceOnly = 1,
	BillMonthly = 2,
	ProofOfPrepurchaseOnly = 3,
	GuestPass = 4,
	HardwarePromo = 5,
	Gift = 6,
	AutoGrant = 7,
	OEMTicket = 8,
	RecurringOption = 9,
	BillOnceOrCDKey = 10,
	Repurchaseable = 11,
	FreeOnDemand = 12,
	Rental = 13,
	CommercialLicense = 14,
	FreeCommercialLicense = 15,
	NumBillingTypes = 16,
}

export default EBillingType;
