/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EBluetoothDeviceType {
	Invalid = 0,
	Unknown = 1,
	Phone = 2,
	Computer = 3,
	Headset = 4,
	Headphones = 5,
	Speakers = 6,
	OtherAudio = 7,
	Mouse = 8,
	Joystick = 9,
	Gamepad = 10,
	Keyboard = 11,
}

export default EBluetoothDeviceType;
