/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EBroadcastImageType {
	None = 0,
	Offline = 1,
	Standby = 2,
	Avatar = 3,
	Summary = 4,
	Background = 5,
	Emoticon = 6,
}

export default EBroadcastImageType;
