/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EBroadcastChatPermission {
	Public = 0,
	OwnsApp = 1,
}

export default EBroadcastChatPermission;
