/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatRoomJoinState {
	Default = 0,
	None = 1,
	Joined = 2,
	TestInvalid = 99,
}

export default EChatRoomJoinState;
