/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatPermission {
	Close = 1,
	Invite = 2,
	EveryoneNotInClanDefault = 8, // Talk
	Talk = 8,
	EveryoneDefault = 10, // Talk|Invite
	Kick = 16,
	Mute = 32,
	SetMetadata = 64,
	ChangePermissions = 128,
	Ban = 256,
	MemberDefault = 282, // Ban|Kick|Talk|Invite
	OfficerDefault = 282, // Ban|Kick|Talk|Invite
	ChangeAccess = 512,
	OwnerDefault = 891, // ChangeAccess|Ban|SetMetadata|Mute|Kick|Talk|Invite|Close
	Mask = 1019,
}

export default EChatPermission;
