/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatFlags {
	Locked = 1,
	InvisibleToFriends = 2,
	Moderated = 4,
	Unjoinable = 8,
}

export default EChatFlags;
