/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatEntryType {
	Invalid = 0,
	ChatMsg = 1,
	Typing = 2,
	InviteGame = 3,
	Emote = 4, // removed "No longer supported by clients"
	LobbyGameStart = 5, // removed "Listen for LobbyGameCreated_t callback instead"
	LeftConversation = 6,
	Entered = 7,
	WasKicked = 8,
	WasBanned = 9,
	Disconnected = 10,
	HistoricalChat = 11,
	Reserved1 = 12,
	Reserved2 = 13,
	LinkBlocked = 14,
}

export default EChatEntryType;
