/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatAction {
	InviteChat = 1,
	Kick = 2,
	Ban = 3,
	UnBan = 4,
	StartVoiceSpeak = 5,
	EndVoiceSpeak = 6,
	LockChat = 7,
	UnlockChat = 8,
	CloseChat = 9,
	SetJoinable = 10,
	SetUnjoinable = 11,
	SetOwner = 12,
	SetInvisibleToFriends = 13,
	SetVisibleToFriends = 14,
	SetModerated = 15,
	SetUnmoderated = 16,
}

export default EChatAction;
