/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatRoomNotificationLevel {
	Invalid = 0,
	None = 1,
	MentionMe = 2,
	MentionAll = 3,
	AllMessages = 4,
}

export default EChatRoomNotificationLevel;
