/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatRoomGroupPermissions {
	Default = 0,
	Valid = 1,
	CanInvite = 2,
	CanKick = 4,
	CanBan = 8,
	CanAdminChannel = 16,
}

export default EChatRoomGroupPermissions;
