/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatRoomType {
	Friend = 1,
	MUC = 2,
	Lobby = 3,
}

export default EChatRoomType;
