/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatRoomGroupRank {
	Default = 0,
	Viewer = 10,
	Guest = 15,
	Member = 20,
	Moderator = 30,
	Officer = 40,
	Owner = 50,
	TestInvalid = 99,
}

export default EChatRoomGroupRank;
