/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatInfoType {
	StateChange = 1,
	InfoUpdate = 2,
	MemberLimitChange = 3,
}

export default EChatInfoType;
