/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatRoomMemberStateChange {
	Invalid = 0,
	Joined = 1,
	Parted = 2,
	Kicked = 3,
	Invited = 4,
	RankChanged = 7,
	InviteDismissed = 8,
	Muted = 9,
	Banned = 10,
	RolesChanged = 12,
}

export default EChatRoomMemberStateChange;
