/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatRoomGroupType {
	Default = 0,
	Unmoderated = 1,
}

export default EChatRoomGroupType;
