/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatRoomMessageReactionType {
	Invalid = 0,
	Emoticon = 1,
	Sticker = 2,
}

export default EChatRoomMessageReactionType;
