/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatRoomGroupAction {
	Default = 0,
	CreateRenameDeleteChannel = 1,
	Kick = 2,
	Ban = 3,
	Invite = 4,
	ChangeTaglineAvatarName = 5,
	Chat = 6,
	ViewHistory = 7,
	ChangeGroupRoles = 8,
	ChangeUserRoles = 9,
	MentionAll = 10,
	SetWatchingBroadcast = 11,
}

export default EChatRoomGroupAction;
