/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EChatMemberStateChange {
	Entered = 1,
	Left = 2,
	Disconnected = 4,
	Kicked = 8,
	Banned = 16,
	VoiceSpeaking = 4096,
	VoiceDoneSpeaking = 8192,
}

export default EChatMemberStateChange;
