/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EChatRoomServerMessage {
	Invalid = 0,
	RenameChatRoom = 1,
	Joined = 2,
	Parted = 3,
	Kicked = 4,
	Invited = 5,
	InviteDismissed = 8,
	ChatRoomTaglineChanged = 9,
	ChatRoomAvatarChanged = 10,
	AppCustom = 11,
}

export default EChatRoomServerMessage;
