/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EClanRelationship {
	None = 0,
	Blocked = 1,
	Invited = 2,
	Member = 3,
	Kicked = 4,
	KickAcknowledged = 5,
	PendingApproval = 6,
	RequestDenied = 7,
}

export default EClanRelationship;
