/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EClanRank {
	None = 0,
	Owner = 1,
	Officer = 2,
	Member = 3,
	Moderator = 4,
}

export default EClanRank;
