/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EClanPermission {
	Nobody = 0,
	Owner = 1,
	Officer = 2,
	OwnerAndOfficer = 3,
	Member = 4,
	Moderator = 8,
	OwnerOfficerModerator = 11, // Owner|Officer|Moderator
	AllMembers = 15, // Owner|Officer|Moderator|Member
	OGGGameOwner = 16,
	NonMember = 128,
}

export default EClanPermission;
