/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EClientNotificationType {
	Invalid = 0,
	DownloadCompleted = 1,
	FriendInvite = 2,
	FriendInGame = 3,
	FriendOnline = 4,
	Achievement = 5,
	LowBattery = 6,
	SystemUpdate = 7,
	FriendMessage = 8,
	GroupChatMessage = 9,
	FriendInviteRollup = 10,
	FamilySharingDeviceAuthorizationChanged = 11,
	FamilySharingStopPlaying = 12,
	FamilySharingLibraryAvailable = 13,
	Screenshot = 14,
	CloudSyncFailure = 15,
	CloudSyncConflict = 16,
	IncomingVoiceChat = 17,
	ClaimSteamDeckRewards = 18,
	GiftReceived = 19,
	ItemAnnouncement = 20,
	HardwareSurvey = 21,
	LowDiskSpace = 22,
	BatteryTemperature = 23,
	DockUnsupportedFirmware = 24,
	PeerContentUpload = 25,
	CannotReadControllerGuideButton = 26,
	Comment = 27,
	Wishlist = 28,
	TradeOffer = 29,
	AsyncGame = 30,
	General = 31,
}

export default EClientNotificationType;
