/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EClientStat {
	P2PConnectionsUDP = 0,
	P2PConnectionsRelay = 1,
	P2PGameConnections = 2,
	P2PVoiceConnections = 3,
	BytesDownloaded = 4,
}

export default EClientStat;
