/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EClientSettingStore {
	Invalid = 0,
	ConfigStore_Install = 1,
	ConfigStore_UserRoaming = 2,
	ConfigStore_UserLocal = 3,
	Registry = 4,
	CustomFunc = 5,
}

export default EClientSettingStore;
