/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EClientPersonaStateFlag {
	Status = 1,
	PlayerName = 2,
	QueryPort = 4,
	SourceID = 8,
	Presence = 16,
	Metadata = 32, // removed
	LastSeen = 64,
	UserClanRank = 128,
	GameExtraInfo = 256,
	GameDataBlob = 512,
	ClanData = 1024,
	Facebook = 2048,
	RichPresence = 4096,
	Broadcast = 8192,
	Watching = 16384,
}

export default EClientPersonaStateFlag;
