/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EClientStatAggregateMethod {
	LatestOnly = 0,
	Sum = 1,
	Event = 2,
	Scalar = 3,
}

export default EClientStatAggregateMethod;
