/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ECloudStoragePersistState {
	Persisted = 0,
	Forgotten = 1,
	Deleted = 2,
}

export default ECloudStoragePersistState;
