/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ECloudPendingRemoteOperation {
	None = 0,
	AppSessionActive = 1,
	UploadInProgress = 2,
	UploadPending = 3,
	AppSessionSuspended = 4,
}

export default ECloudPendingRemoteOperation;
