/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ECodecUsagePlatform {
	Unknown = 0,
	Windows = 1,
	MacOS = 2,
	Linux = 3,
	SteamDeck = 4,
}

export default ECodecUsagePlatform;
