/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ECodecUsageReason {
	Unknown = 0,
	RemotePlay = 1,
	Broadcasting = 2,
	GameVideo = 3,
}

export default ECodecUsageReason;
