/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EColorProfile {
	Invalid = 0,
	Native = 1,
	Standard = 2,
	Vivid = 3,
}

export default EColorProfile;
