/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ECommunityItemClass {
	Invalid = 0,
	Badge = 1,
	GameCard = 2,
	ProfileBackground = 3,
	Emoticon = 4,
	BoosterPack = 5,
	Consumable = 6,
	GameGoo = 7,
	ProfileModifier = 8,
	Scene = 9,
	SalienItem = 10,
	Sticker = 11,
	ChatEffect = 12,
	MiniProfileBackground = 13,
	AvatarFrame = 14,
	AnimatedAvatar = 15,
	SteamDeckKeyboardSkin = 16,
	SteamDeckStartupMovie = 17,
}

export default ECommunityItemClass;
