/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EContentHubDiscountFilterType {
	None = 0,
	DiscountsOnly = 1,
	PrioritizeDiscounts = 2,
}

export default EContentHubDiscountFilterType;
