/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EContentDescriptorID {
	FrequentNudityOrSexualContent = 1,
	FrequentViolenceOrGore = 2,
	StrongSexualContent = 3,
	UNUSED_4 = 4,
	AnyMatureContent = 5,
}

export default EContentDescriptorID;
