/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EContentDownloadSourceType {
	Invalid = 0,
	CS = 1,
	CDN = 2,
	LCS = 3,
	ProxyCache = 4,
	LANPeer = 5,
	SLS = 6,
	SteamCache = 7,
	OpenCache = 8,
	LANCache = 9,
}

export default EContentDownloadSourceType;
