/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EContentDeltaChunkDataLocation {
	InProtobuf = 0,
	AfterProtobuf = 1,
}

export default EContentDeltaChunkDataLocation;
