/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ECPUGovernor {
	Invalid = 0,
	Perf = 1,
	Powersave = 2,
	Manual = 3,
}

export default ECPUGovernor;
