/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EDepotFileFlag {
	UserConfig = 1,
	VersionedUserConfig = 2,
	Encrypted = 4,
	ReadOnly = 8,
	Hidden = 16,
	Executable = 32,
	Directory = 64,
	CustomExecutable = 128,
	InstallScript = 256,
	Symlink = 512,
}

export default EDepotFileFlag;
