/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EDRMBlobDownloadErrorDetail {
	None = 0,
	DownloadFailed = 1,
	TargetLocked = 2,
	OpenZip = 3,
	ReadZipDirectory = 4,
	UnexpectedZipEntry = 5,
	UnzipFullFile = 6,
	UnknownBlobType = 7,
	UnzipStrips = 8,
	UnzipMergeGuid = 9,
	UnzipSignature = 10,
	ApplyStrips = 11,
	ApplyMergeGuid = 12,
	ApplySignature = 13,
	AppIdMismatch = 14,
	AppIdUnexpected = 15,
	AppliedSignatureCorrupt = 16,
	ApplyValveSignatureHeader = 17,
	UnzipValveSignatureHeader = 18,
	PathManipulationError = 19,
	TargetLocked_Base = 65536,
	TargetLocked_Max = 131071,
	NextBase = 131072,
}

export default EDRMBlobDownloadErrorDetail;
