/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EDRMBlobDownloadType {
	Error = 0,
	File = 1,
	Parts = 2,
	Compressed = 4,
	AllMask = 7,
	IsJob = 8,
	HighPriority = 16,
	AddTimestamp = 32,
	LowPriority = 64,
}

export default EDRMBlobDownloadType;
