/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EExternalAccountType {
	k_EExternalNone = 0,
	k_EExternalSteamAccount = 1,
	k_EExternalGoogleAccount = 2,
	k_EExternalFacebookAccount = 3,
	k_EExternalTwitterAccount = 4,
	k_EExternalTwitchAccount = 5,
	k_EExternalYouTubeChannelAccount = 6,
	k_EExternalFacebookPage = 7,
}

export default EExternalAccountType;
