/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EFrameAccumulatedStat {
	FPS = 0,
	CaptureDurationMS = 1,
	ConvertDurationMS = 2,
	EncodeDurationMS = 3,
	SteamDurationMS = 4,
	ServerDurationMS = 5,
	NetworkDurationMS = 6,
	DecodeDurationMS = 7,
	DisplayDurationMS = 8,
	ClientDurationMS = 9,
	FrameDurationMS = 10,
	InputLatencyMS = 11,
	GameLatencyMS = 12,
	RoundTripLatencyMS = 13,
	PingTimeMS = 14,
	ServerBitrateKbitPerSec = 15,
	ClientBitrateKbitPerSec = 16,
	LinkBandwidthKbitPerSec = 17,
	PacketLossPercentage = 18,
}

export default EFrameAccumulatedStat;
