/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EFriendFlags {
	None = 0,
	Blocked = 1,
	FriendshipRequested = 2,
	Immediate = 4,
	ClanMember = 8,
	OnGameServer = 16,
	RequestingFriendship = 128,
	RequestingInfo = 256,
	Ignored = 512,
	IgnoredFriend = 1024,
	Suggested = 2048,
	ChatMember = 4096,
	FlagAll = 65535,
}

export default EFriendFlags;
