/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EGameSearchResult {
	Invalid = 0,
	SearchInProgress = 1,
	SearchFailedNoHosts = 2,
	SearchGameFound = 3,
	SearchCompleteAccepted = 4,
	SearchCompleteDeclined = 5,
	SearchCanceled = 6,
}

export default EGameSearchResult;
