/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EGameSearchAction {
	None = 0,
	Accept = 1,
	Decline = 2,
	Cancel = 3,
}

export default EGameSearchAction;
