/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EGetChannelsAlgorithm {
	Default = 1,
	Friends = 2,
	Featured = 3,
	Developer = 4,
	Following = 5,
}

export default EGetChannelsAlgorithm;
