/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EGetGamesAlgorithm {
	Default = 1,
	MostPlayed = 2,
	PopularNew = 3,
}

export default EGetGamesAlgorithm;
