/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EGPUPerformanceLevel {
	Invalid = 0,
	Auto = 1,
	Manual = 2,
	Low = 3,
	High = 4,
	Profiling = 5,
}

export default EGPUPerformanceLevel;
