/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EGraphicsPerfOverlayLevel {
	Hidden = 0,
	Basic = 1,
	Medium = 2,
	Full = 3,
	Minimal = 4,
}

export default EGraphicsPerfOverlayLevel;
