/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EHDRToneMapOperator {
	Invalid = 0,
	Uncharted = 1,
	Reinhard = 2,
}

export default EHDRToneMapOperator;
