/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EHIDDeviceLocation {
	Local = 0,
	Remote = 2,
	Any = 3,
}

export default EHIDDeviceLocation;
