/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EHIDDeviceDisconnectMethod {
	Unknown = 0,
	Bluetooth = 1,
	FeatureReport = 2,
	OutputReport = 3,
}

export default EHIDDeviceDisconnectMethod;
