/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EInputMode {
	Unknown = 0,
	Mouse = 1,
	Controller = 2,
	MouseAndController = 3,
}

export default EInputMode;
