/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EInternalAccountType {
	k_EInternalSteamAccountType = 1,
	k_EInternalClanType = 2,
	k_EInternalAppType = 3,
	k_EInternalBroadcastChannelType = 4,
}

export default EInternalAccountType;
