/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EIntroducerRouting {
	FileShare = 0, // removed
	P2PVoiceChat = 1,
	P2PNetworking = 2,
}

export default EIntroducerRouting;
