/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EJSRegisterMethodType {
	Invalid = 0,
	Function = 1,
	Callback = 2,
	Promise = 3,
}

export default EJSRegisterMethodType;
