/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ELauncherType {
	Default = 0,
	PerfectWorld = 1,
	Nexon = 2,
	CmdLine = 3,
	CSGO = 4,
	ClientUI = 5,
	Headless = 6,
	SteamChina = 7,
	SingleApp = 8,
	GameServer = 9,
}

export default ELauncherType;
