/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ELeaderboardSortMethod {
	None = 0,
	Ascending = 1,
	Descending = 2,
}

export default ELeaderboardSortMethod;
