/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ELicenseFlags {
	None = 0,
	Renew = 1,
	RenewalFailed = 2,
	Pending = 4,
	Expired = 8,
	CancelledByUser = 16,
	CancelledByAdmin = 32,
	LowViolenceContent = 64,
	ImportedFromSteam2 = 128,
	ForceRunRestriction = 256,
	RegionRestrictionExpired = 512,
	CancelledByFriendlyFraudLock = 1024,
	NotActivated = 2048,
	PendingRefund = 8192,
	Borrowed = 16384,
	ReleaseStateOverride = 32768,
	CancelledByPartner = 262144,
	NonPermanent = 524288,
	PreferredOwner = 1048576,
}

export default ELicenseFlags;
