/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ELicenseType {
	NoLicense = 0,
	SinglePurchase = 1,
	SinglePurchaseLimitedUse = 2,
	RecurringCharge = 3,
	RecurringChargeLimitedUse = 4,
	RecurringChargeLimitedUseWithOverages = 5,
	RecurringOption = 6,
	LimitedUseDelayedActivation = 7,
}

export default ELicenseType;
