/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ELobbyType {
	Private = 0,
	FriendsOnly = 1,
	Public = 2,
	Invisible = 3,
	PrivateUnique = 4,
}

export default ELobbyType;
