/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ELobbyFilterType {
	String = 0,
	Numerical = 1,
	SlotsAvailable = 2,
	NearValue = 3,
	Distance = 4,
}

export default ELobbyFilterType;
