/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ELobbyComparison {
	EqualToOrLessThan = -2,
	LessThan = -1,
	Equal = 0,
	GreaterThan = 1,
	EqualToOrGreaterThan = 2,
	NotEqual = 3,
}

export default ELobbyComparison;
