/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EMarketingMessageFlags {
	None = 0,
	HighPriority = 1,
	PlatformWindows = 2,
	PlatformMac = 4,
	PlatformLinux = 8,
	PlatformRestrictions = 14, // PlatformWindows|PlatformMac|PlatformLinux
}

export default EMarketingMessageFlags;
