/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EMarketingMessageVisibility {
	Beta = 1,
	Public = 2,
}

export default EMarketingMessageVisibility;
