/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EMarketingMessageType {
	Invalid = 0,
	NowAvailable = 1,
	WeekendDeal = 2,
	PrePurchase = 3,
	PlayNow = 4,
	PreloadNow = 5,
	General = 6,
	DemoQuit = 7,
	Gifting = 8,
	EJsKorner = 9,
}

export default EMarketingMessageType;
