/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EMarketingMessageAssociationType {
	NoAssociation = 0,
	AppAssociation = 1,
	SubscriptionAssociation = 2,
	PublisherAssociation = 3,
	GenreAssociation = 4,
	BundleAssociation = 5,
}

export default EMarketingMessageAssociationType;
