/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EMarketingMessageLookupType {
	Invalid = 0,
	ByGID = 1,
	Active = 2,
	ByTitleWithType = 3,
	ByGIDList = 4,
}

export default EMarketingMessageLookupType;
