/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EMouseMode {
	Unknown = 0,
	RelativeCursor = 1,
	AbsoluteCursor = 2,
	Touch = 3,
	Relative = 4,
}

export default EMouseMode;
