/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EMsgClanAccountFlags {
	k_EMsgClanAccountFlagPublic = 1,
	k_EMsgClanAccountFlagLarge = 2,
	k_EMsgClanAccountFlagLocked = 4,
	k_EMsgClanAccountFlagDisabled = 8,
	k_EMsgClanAccountFlagOGG = 16,
}

export default EMsgClanAccountFlags;
