/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ENewsUpdateType {
	AppNews = 0,
	SteamAds = 1,
	SteamNews = 2,
	CDDBUpdate = 3,
	ClientUpdate = 4,
}

export default ENewsUpdateType;
