/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ENewSteamAnnouncementState {
	Invalid = 0,
	AllRead = 1,
	NewAnnouncement = 2,
	FeaturedAnnouncement = 3,
}

export default ENewSteamAnnouncementState;
