/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ENotificationSetting {
	NotifyUseDefault = 0,
	Always = 1,
	Never = 2,
}

export default ENotificationSetting;
