/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EOSBranch {
	Unknown = 0,
	Release = 1,
	ReleaseCandidate = 2,
	Beta = 3,
	BetaCandidate = 4,
	Main = 5,
	Staging = 6,
}

export default EOSBranch;
