/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EPackageStatus {
	Available = 0,
	Preorder = 1,
	Unavailable = 2,
	Invalid = 3,
}

export default EPackageStatus;
