/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EPersonaStateFlag {
	HasRichPresence = 1,
	InJoinableGame = 2,
	Golden = 4,
	RemotePlayTogether = 8,
	ClientTypeWeb = 256,
	ClientTypeMobile = 512,
	ClientTypeTenfoot = 1024,
	ClientTypeVR = 2048,
	LaunchTypeGamepad = 4096,
	LaunchTypeCompatTool = 8192,
}

export default EPersonaStateFlag;
