/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EPlaytestStatus {
	None = 0,
	Pending = 1,
	Invited = 2,
	Granted = 3,
}

export default EPlaytestStatus;
