/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EPlatformType {
	Unknown = 0,
	Win32 = 1,
	Win64 = 2,
	Linux = 3, // removed "split to Linux64 and Linux32"
	Linux64 = 3,
	OSX = 4,
	PS3 = 5,
	Linux32 = 6,
}

export default EPlatformType;
