/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EProfileCustomizationStyle {
	Default = 0,
	Selected = 1,
	Rarest = 2,
	MostRecent = 3,
	Random = 4,
	HighestRated = 5,
}

export default EProfileCustomizationStyle;
