/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EProfileCustomizationType {
	Invalid = 0,
	RareAchievementShowcase = 1,
	GameCollector = 2,
	ItemShowcase = 3,
	TradeShowcase = 4,
	Badges = 5,
	FavoriteGame = 6,
	ScreenshotShowcase = 7,
	CustomText = 8,
	FavoriteGroup = 9,
	Recommendation = 10,
	WorkshopItem = 11,
	MyWorkshop = 12,
	ArtworkShowcase = 13,
	VideoShowcase = 14,
	Guides = 15,
	MyGuides = 16,
	Achievements = 17,
	Greenlight = 18,
	MyGreenlight = 19,
	Salien = 20,
	LoyaltyRewardReactions = 21,
	SingleArtworkShowcase = 22,
	AchievementsCompletionist = 23,
	Replay = 24,
}

export default EProfileCustomizationType;
