/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EProvideDeckFeedbackPreference {
	Unset = 0,
	Yes = 1,
	No = 2,
}

export default EProvideDeckFeedbackPreference;
