/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EPublishedFileForSaleStatus {
	NotForSale = 0,
	PendingApproval = 1,
	ApprovedForSale = 2,
	RejectedForSale = 3,
	NoLongerForSale = 4,
	TentativeApproval = 5,
}

export default EPublishedFileForSaleStatus;
