/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EPublishedFileRevision {
	Default = 0,
	Latest = 1,
	ApprovedSnapshot = 2,
	ApprovedSnapshot_China = 3,
	RejectedSnapshot = 4,
	RejectedSnapshot_China = 5,
}

export default EPublishedFileRevision;
