/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EPublishedFileStorageSystem {
	Invalid = 0,
	LegacyCloud = 1,
	Depot = 2,
	UGCCloud = 3,
}

export default EPublishedFileStorageSystem;
