/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EPublishedFileInappropriateProvider {
	Invalid = 0,
	Google = 1,
	Amazon = 2,
}

export default EPublishedFileInappropriateProvider;
