/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ERegionCode {
	USEast = 0,
	USWest = 1,
	SouthAmerica = 2,
	Europe = 3,
	Asia = 4,
	Australia = 5,
	MiddleEast = 6,
	Africa = 7,
	World = 255,
}

export default ERegionCode;
