/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ERemoteClientService {
	None = 0,
	RemoteControl = 1,
	GameStreaming = 2,
	SiteLicense = 4,
	ContentCache = 8,
	ContentServer = 16,
}

export default ERemoteClientService;
