/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ERemoteClientBroadcastMsg {
	Discovery = 0,
	Status = 1,
	Offline = 2,
	AuthorizationRequest = 3,
	AuthorizationResponse = 4,
	StreamingRequest = 5,
	StreamingResponse = 6,
	ProofRequest = 7,
	ProofResponse = 8,
	AuthorizationCancelRequest = 9,
	StreamingCancelRequest = 10,
	ClientIDDeconflict = 11,
	StreamTransportSignal = 12,
	StreamingProgress = 13,
	AuthorizationConfirmed = 14,
}

export default ERemoteClientBroadcastMsg;
