/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ERemoteDeviceAuthorizationResult {
	Success = 0,
	Denied = 1,
	NotLoggedIn = 2,
	Offline = 3,
	Busy = 4,
	InProgress = 5,
	TimedOut = 6,
	Failed = 7,
	Canceled = 8,
}

export default ERemoteDeviceAuthorizationResult;
