/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ERemoteDeviceStreamingResult {
	Success = 0,
	Unauthorized = 1,
	ScreenLocked = 2,
	Failed = 3,
	Busy = 4,
	InProgress = 5,
	Canceled = 6,
	DriversNotInstalled = 7,
	Disabled = 8,
	BroadcastingActive = 9,
	VRActive = 10,
	PINRequired = 11,
	TransportUnavailable = 12,
	Invisible = 13,
	GameLaunchFailed = 14,
}

export default ERemoteDeviceStreamingResult;
