/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ERemoteStoragePlatform {
	All = -1,
	None = 0,
	Windows = 1,
	OSX = 2,
	PS3 = 4,
	Linux = 8,
	Switch = 16,
	Android = 32,
	IPhoneOS = 64,
}

export default ERemoteStoragePlatform;
