/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EScalingFilter {
	Invalid = 0,
	FSR = 1,
	Nearest = 2,
	Integer = 3,
	Linear = 4,
	NIS = 5,
}

export default EScalingFilter;
