/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESDCardFormatStage {
	Invalid = 0,
	Starting = 1,
	Testing = 2,
	Rescuing = 3,
	Formatting = 4,
	Finalizing = 5,
}

export default ESDCardFormatStage;
