/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EServerFlags {
	None = 0,
	Active = 1,
	Secure = 2,
	Dedicated = 4,
	Linux = 8,
	Passworded = 16,
	Private = 32,
}

export default EServerFlags;
