/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESessionPersistence {
	Invalid = -1,
	Ephemeral = 0,
	Persistent = 1,
}

export default ESessionPersistence;
