/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESplitScalingFilter {
	Invalid = 0,
	Linear = 1,
	Nearest = 2,
	FSR = 3,
	NIS = 4,
}

export default ESplitScalingFilter;
