/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESplitScalingScaler {
	Invalid = 0,
	Auto = 1,
	Integer = 2,
	Fit = 3,
	Fill = 4,
	Stretch = 5,
}

export default ESplitScalingScaler;
