/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ESteamDeckCompatibilityResultDisplayType {
	Invisible = 0,
	Informational = 1,
	Unsupported = 2,
	Playable = 3,
	Verified = 4,
}

export default ESteamDeckCompatibilityResultDisplayType;
