/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESteamDeckCompatibilityFeedback {
	Unset = 0,
	Agree = 1,
	Disagree = 2,
	Ignore = 3,
}

export default ESteamDeckCompatibilityFeedback;
