/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESteamNetworkingSocketsCipher {
	INVALID = 0,
	NULL = 1,
	AES_256_GCM = 2,
}

export default ESteamNetworkingSocketsCipher;
