/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ESteamNetworkingUDPMsgID {
	ChallengeRequest = 32,
	ChallengeReply = 33,
	ConnectRequest = 34,
	ConnectOK = 35,
	ConnectionClosed = 36,
	NoConnection = 37,
}

export default ESteamNetworkingUDPMsgID;
