/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ESteamPipeOperationType {
	Invalid = 0,
	DecryptCPU = 1,
	DiskRead = 2,
	DiskWrite = 3,
}

export default ESteamPipeOperationType;
