/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ESteamDeckCompatibilityCategory {
	Unknown = 0,
	Unsupported = 1,
	Playable = 2,
	Verified = 3,
}

export default ESteamDeckCompatibilityCategory;
