/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESteamTVContentTemplate {
	Invalid = 0,
	Takeover = 1,
	SingleGame = 2,
	GameList = 3,
	QuickExplore = 4,
	ConveyorBelt = 5,
	WatchParty = 6,
	Developer = 7,
	Event = 8,
}

export default ESteamTVContentTemplate;
