/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStoreAppType {
	Game = 0,
	Demo = 1,
	Mod = 2,
	Movie = 3,
	DLC = 4,
	Guide = 5,
	Software = 6,
	Video = 7,
	Series = 8,
	Episode = 9,
	Hardware = 10,
	Music = 11,
	Beta = 12,
	Tool = 13,
	Advertising = 14,
}

export default EStoreAppType;
