/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStoreDiscoveryQueueType {
	New = 0,
	ComingSoon = 1,
	Recommended = 2,
	EveryNewRelease = 3,
	MLRecommender = 5,
	WishlistOnSale = 6,
	DLC = 7,
	DLCOnSale = 8,
	RecommendedComingSoon = 9,
	RecommendedFree = 10,
	RecommendedOnSale = 11,
	RecommendedDemos = 12,
	DLCNewReleases = 13,
	DLCTopSellers = 14,
	MAX = 15,
}

export default EStoreDiscoveryQueueType;
