/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStoreItemType {
	Invalid = -1,
	App = 0,
	Package = 1,
	Bundle = 2,
	Mtx = 3,
	Tag = 4,
	Creator = 5,
}

export default EStoreItemType;
