/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStorageDriveMediaType {
	Invalid = 0,
	Unknown = 1,
	HDD = 2,
	SSD = 3,
	Removable = 4,
}

export default EStorageDriveMediaType;
