/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStoreCategoryType {
	Category = 0,
	SupportedPlayers = 1,
	Feature = 2,
	ControllerSupport = 3,
	CloudGaming = 4,
	MAX = 5,
}

export default EStoreCategoryType;
