/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStorageBlockContentType {
	Invalid = 0,
	Unknown = 1,
	FileSystem = 2,
	Crypto = 3,
	Raid = 4,
}

export default EStorageBlockContentType;
