/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStorageBlockFileSystemType {
	Invalid = 0,
	Unknown = 1,
	VFat = 2,
	Ext4 = 3,
}

export default EStorageBlockFileSystemType;
