/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamControllerConfigMsg {
	RequestConfigsForApp = 0,
	ConfigResponse = 1,
	PersonalizationResponse = 2,
	ActiveConfigChange = 3,
	RequestActiveConfig = 4,
}

export default EStreamControllerConfigMsg;
