/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamFrameEvent {
	InputEventStart = 0,
	InputEventSend = 1,
	InputEventRecv = 2,
	InputEventQueued = 3,
	InputEventHandled = 4,
	Start = 5,
	CaptureBegin = 6,
	CaptureEnd = 7,
	ConvertBegin = 8,
	ConvertEnd = 9,
	EncodeBegin = 10,
	EncodeEnd = 11,
	Send = 12,
	Recv = 13,
	DecodeBegin = 14,
	DecodeEnd = 15,
	UploadBegin = 16,
	UploadEnd = 17,
	Complete = 18,
}

export default EStreamFrameEvent;
