/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamHostPlayAudioPreference {
	k_EStreamHostPlayAudioDefault = 0,
	k_EStreamHostPlayAudioAlways = 1,
}

export default EStreamHostPlayAudioPreference;
