/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamInterface {
	Default = 0,
	RecentGames = 1,
	BigPicture = 2,
	Desktop = 3,
}

export default EStreamInterface;
