/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamMouseButton {
	Left = 1,
	Right = 2,
	Middle = 16,
	X1 = 32,
	X2 = 64,
	Unknown = 4096,
}

export default EStreamMouseButton;
