/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamChannel {
	Invalid = -1,
	Discovery = 0,
	Control = 1,
	Stats = 2,
	DataChannelStart = 3,
}

export default EStreamChannel;
