/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamQualityPreference {
	Automatic = -1,
	Fast = 1,
	Balanced = 2,
	Beautiful = 3,
}

export default EStreamQualityPreference;
