/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamColorspace {
	Unknown = 0,
	BT601 = 1,
	BT601_Full = 2,
	BT709 = 3,
	BT709_Full = 4,
}

export default EStreamColorspace;
