/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamingDataType {
	AudioData = 0,
	VideoData = 1,
	MicrophoneData = 2,
	NeptuneData = 3,
}

export default EStreamingDataType;
