/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamMouseWheelDirection {
	Down = -120,
	Left = 3,
	Right = 4,
	Up = 120,
}

export default EStreamMouseWheelDirection;
