/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamStatsMessage {
	FrameEvents = 1,
	DebugDump = 2,
	LogMessage = 3,
	LogUploadBegin = 4,
	LogUploadData = 5,
	LogUploadComplete = 6,
}

export default EStreamStatsMessage;
