/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamDeviceFormFactor {
	Unknown = 0,
	Phone = 1,
	Tablet = 2,
	Computer = 3,
	TV = 4,
}

export default EStreamDeviceFormFactor;
