/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamFramerateLimiter {
	SlowCapture = 1,
	SlowConvert = 2,
	SlowEncode = 4,
	SlowNetwork = 8,
	SlowDecode = 16,
	SlowGame = 32,
	SlowDisplay = 64,
}

export default EStreamFramerateLimiter;
