/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamP2PScope {
	Automatic = 0,
	Disabled = 1,
	OnlyMe = 2,
	Friends = 3,
	Everyone = 4,
}

export default EStreamP2PScope;
