/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EStreamVersion {
	None = 0,
	Current = 1,
}

export default EStreamVersion;
