/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamActivity {
	Idle = 1,
	Game = 2,
	Desktop = 3,
	SecureDesktop = 4,
	Music = 5,
}

export default EStreamActivity;
