/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamTransport {
	None = 0,
	UDP = 1,
	UDPRelay = 2,
	WebRTC = 3,
	SDR = 4,
	UDP_SNS = 5,
	UDPRelay_SNS = 6,
}

export default EStreamTransport;
