/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamVideoCodec {
	None = 0,
	Raw = 1,
	VP8 = 2,
	VP9 = 3,
	H264 = 4,
	HEVC = 5,
	ORBX1 = 6,
	ORBX2 = 7,
}

export default EStreamVideoCodec;
