/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamAudioCodec {
	None = 0,
	Raw = 1,
	Vorbis = 2,
	Opus = 3,
	MP3 = 4,
	AAC = 5,
}

export default EStreamAudioCodec;
