/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EStreamFrameResult {
	Pending = 0,
	Displayed = 1,
	DroppedNetworkSlow = 2,
	DroppedNetworkLost = 3,
	DroppedDecodeSlow = 4,
	DroppedDecodeCorrupt = 5,
	DroppedLate = 6,
	DroppedReset = 7,
}

export default EStreamFrameResult;
