/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ESystemAudioChannel {
	Invalid = 0,
	Aggregated = 1,
	FrontLeft = 2,
	FrontRight = 3,
	LFE = 4,
	BackLeft = 5,
	BackRight = 6,
	FrontCenter = 7,
	Unknown = 8,
	Mono = 9,
}

export default ESystemAudioChannel;
