/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESystemIMType {
	RawText = 0,
	InvalidCard = 1,
	RecurringPurchaseFailed = 2,
	CardWillExpire = 3,
	SubscriptionExpired = 4,
	GuestPassReceived = 5,
	GuestPassGranted = 6,
	GiftRevoked = 7,
	SupportMessage = 8,
	SupportMessageClearAlert = 9,
}

export default ESystemIMType;
