/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESystemUpdateNotificationType {
	Invalid = 0,
	Available = 1,
	NeedsRestart = 2,
}

export default ESystemUpdateNotificationType;
