/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESystemAudioPortType {
	Invalid = 0,
	Unknown = 1,
	Audio32f = 2,
	Midi8b = 3,
	Video32RGBA = 4,
}

export default ESystemAudioPortType;
