/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ESystemDisplayCompatibilityMode {
	Invalid = 0,
	None = 1,
	MinimalBandwith = 2,
}

export default ESystemDisplayCompatibilityMode;
