/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ESystemFanControlMode {
	Invalid = 0,
	Disabled = 1,
	Default = 2,
}

export default ESystemFanControlMode;
