/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ETextFilterSetting {
	SteamLabOptedOut = 0,
	Enabled = 1,
	EnabledAllowProfanity = 2,
	Disabled = 3,
}

export default ETextFilterSetting;
