/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum ETokenRenewalType {
	None = 0,
	Allow = 1,
}

export default ETokenRenewalType;
