/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ETouchGesture {
	None = 0,
	Touch = 1,
	Tap = 2,
	DoubleTap = 3,
	ShortPress = 4,
	LongPress = 5,
	LongTap = 6,
	TwoFingerTap = 7,
	TapCancelled = 8,
	PinchBegin = 9,
	PinchUpdate = 10,
	PinchEnd = 11,
	FlingStart = 12,
	FlingCancelled = 13,
}

export default ETouchGesture;
