/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ETradeOfferConfirmationMethod {
	Invalid = 0,
	Email = 1,
	MobileApp = 2,
}

export default ETradeOfferConfirmationMethod;
