/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum ETradeOfferState {
	Invalid = 1,
	Active = 2,
	Accepted = 3,
	Countered = 4,
	Expired = 5,
	Canceled = 6,
	Declined = 7,
	InvalidItems = 8,
	CreatedNeedsConfirmation = 9,
	CanceledBySecondFactor = 10,
	InEscrow = 11,
}

export default ETradeOfferState;
