/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EUCMFilePrivacyState {
	Invalid = -1,
	Private = 2,
	FriendsOnly = 4,
	Public = 8,
	Unlisted = 16,
	All = 30, // Public|FriendsOnly|Private|Unlisted
}

export default EUCMFilePrivacyState;
