/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EUdpPacketType {
	Invalid = 0,
	ChallengeReq = 1,
	Challenge = 2,
	Connect = 3,
	Accept = 4,
	Disconnect = 5,
	Data = 6,
	Datagram = 7,
	Max = 8,
}

export default EUdpPacketType;
