/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EUpdaterType {
	Invalid = 0,
	Client = 1,
	OS = 2,
	BIOS = 3,
	Aggregated = 4,
	Test1 = 5,
	Test2 = 6,
	Dummy = 7,
}

export default EUpdaterType;
