/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EUpdaterState {
	Invalid = 0,
	UpToDate = 2,
	Checking = 3,
	Available = 4,
	Applying = 5,
	ClientRestartPending = 6,
	SystemRestartPending = 7,
}

export default EUpdaterState;
