/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EUserReviewScore {
	None = 0,
	OverwhelminglyNegative = 1,
	VeryNegative = 2,
	Negative = 3,
	MostlyNegative = 4,
	Mixed = 5,
	MostlyPositive = 6,
	Positive = 7,
	VeryPositive = 8,
	OverwhelminglyPositive = 9,
}

export default EUserReviewScore;
