/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EUserReviewScorePreference {
	Unset = 0,
	IncludeAll = 1,
	ExcludeBombs = 2,
}

export default EUserReviewScorePreference;
