/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EValveIndexComponent {
	Unknown = 0,
	HMD = 1,
	LeftKnuckle = 2,
	RightKnuckle = 3,
}

export default EValveIndexComponent;
