/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EVideoFormat {
	None = 0,
	YV12 = 1,
	Accel = 2,
}

export default EVideoFormat;
