/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EVoiceCallState {
	None = 0,
	ScheduledInitiate = 1,
	RequestedMicAccess = 2,
	LocalMicOnly = 3,
	CreatePeerConnection = 4,
	InitatedWebRTCSession = 5,
	WebRTCConnectedWaitingOnIceConnected = 6,
	RequestedPermission = 7,
	NotifyingVoiceChatOfWebRTCSession = 8,
	Connected = 9,
}

export default EVoiceCallState;
