/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:45:19 GMT-0400 (Eastern Daylight Time)

enum EWorkshopFileAction {
	Played = 0,
	Completed = 1,
}

export default EWorkshopFileAction;
