/* eslint-disable */
// Auto-generated by generate-enums script on Mon Aug 12 2024 18:59:20 GMT-0400 (Eastern Daylight Time)

enum EWorkshopEnumerationType {
	RankedByVote = 0,
	Recent = 1,
	Trending = 2,
	FavoriteOfFriends = 3,
	VotedByFriends = 4,
	ContentByFriends = 5,
	RecentFromFollowedUsers = 6,
}

export default EWorkshopEnumerationType;
